{$EXTENDEDSYNTAX ON}
{$VARSTRINGCHECKS ON}
{$TYPEDADDRESS OFF}
{$OPENSTRINGS ON}
{$LONGSTRINGS ON}

{$IOCHECKS ON}
{$OVERFLOWCHECKS OFF}

{$TYPEINFO OFF}
{$DEBUGINFO ON}

{$S-,Z1}

{$IFDEF FPC} // freepascal
  {$SMARTLINK ON}
  {$I jedi.inc}
{$ELSE} // delphi
  {$E-}
  {$LOCALSYMBOLS ON}
  {$APPTYPE GUI}
  {$MINSTACKSIZE $00010000}
  {$MAXSTACKSIZE $01000000}
  {$IMAGEBASE $00400000}

  {$ALIGN ON}
  {$BOOLEVAL OFF}
  {$STACKFRAMES OFF}

  {$WRITEABLECONST ON}
  {$SAFEDIVIDE OFF}
  {$IMPORTEDDATA OFF}
  {$DEFINITIONINFO ON}

  {$IFOPT O-}
    {$DEFINE DEBUG}
  {$ENDIF}

  {$F-,K-,N+}
{$ENDIF}

{$IFDEF DEBUG}
  {$ASSERTIONS ON}
  {$RANGECHECKS ON}
{$ELSE}
  {$ASSERTIONS OFF}
  {$RANGECHECKS OFF}
{$ENDIF}

