unit FokoFilePrintForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
  {$IFDEF FPC}, DB, FokoListReport{$ELSE}, QuickRpt, QRCtrls{$ENDIF};
  
type
  TFokoFilePrintForm=class(TForm)
    {$IFNDEF FPC}
    QuickRep1: TQuickRep;
    QRBand1: TQRBand;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRShape1: TQRShape;
    QRShape3: TQRShape;
    QRBand3: TQRBand;
    QRDBText3: TQRDBText;
    QRImage1: TQRImage;
    QRImage2: TQRImage;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRImage3: TQRImage;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRBand4: TQRBand;
    QRSysData1: TQRSysData;
    QRSysData2: TQRSysData;
    QRShape2: TQRShape;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel11: TQRLabel;
    {$ENDIF}
    procedure _PROC_005CB970(Sender : TObject);
    {$IFDEF FPC}
    /// Creates an owned LazReport builder for a caller-supplied active Table20.
    function CreateFokoListReport(const ATemplateFileName: string;
      ADataSet: TDataSet): TFokoListReport;
    {$ENDIF}
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form23: TFokoFilePrintForm;
  GlobalVar_025358D0: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC}
{$R *.LFM}
{$ELSE}
{$R *.DFM}
{$ENDIF}

procedure TFokoFilePrintForm._PROC_005CB970(Sender : TObject);
begin
  Dec(GlobalVar_025358D0);
end;

{$IFDEF FPC}
function TFokoFilePrintForm.CreateFokoListReport(const ATemplateFileName: string;
  ADataSet: TDataSet): TFokoListReport;
begin
  Result := TFokoListReport.Create(Self, ATemplateFileName, ADataSet);
end;
{$ENDIF}

end.