unit SingleColumnA4ReportForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
  {$IFDEF FPC}, DB, Unit5ListReport{$ELSE}, QuickRpt, QRCtrls{$ENDIF};
type
  TSingleColumnA4ReportForm=class(TForm)
    {$IFNDEF FPC}
    QuickRep1: TQuickRep;
    QRBand1: TQRBand;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRShape1: TQRShape;
    QRShape3: TQRShape;
    QRBand3: TQRBand;
    QRDBText3: TQRDBText;
    QRMemo1: TQRMemo;
    QRImage1: TQRImage;
    QRImage2: TQRImage;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRDBText10: TQRDBText;
    QRDBText11: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText14: TQRDBText;
    QRDBText15: TQRDBText;
    QRImage3: TQRImage;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRBand4: TQRBand;
    QRSysData1: TQRSysData;
    QRSysData2: TQRSysData;
    QRShape2: TQRShape;
    QRLabel3: TQRLabel;
    {$ENDIF}
    procedure _PROC_00539EBC(Sender : TObject);
    {$IFDEF FPC}
    /// Creates an owned LazReport builder for a caller-provided dataset.
    function CreateUnit5ListReport(ADataSet: TDataSet): TUnit5ListReport;
    {$ENDIF}
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form5: TSingleColumnA4ReportForm;
  GlobalVar_0061DFA0: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC}
{$R *.LFM}
{$ELSE}
{$R *.DFM}
{$ENDIF}

procedure TSingleColumnA4ReportForm._PROC_00539EBC(Sender : TObject);
begin
  Dec(GlobalVar_0061DFA0);
end;

{$IFDEF FPC}
function TSingleColumnA4ReportForm.CreateUnit5ListReport(
  ADataSet: TDataSet): TUnit5ListReport;
begin
  Result := TUnit5ListReport.Create(Self, ADataSet);
end;
{$ENDIF}

end.
