unit SingleColumnA4ReportVariantForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
  {$IFDEF FPC}, DB, Unit15ListReport{$ELSE}, QuickRpt, QRCtrls{$ENDIF};
type
  TSingleColumnA4ReportVariantForm=class(TForm)
    {$IFNDEF FPC}
    QuickRep1: TQuickRep;
    QRBand1: TQRBand;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRShape1: TQRShape;
    QRShape3: TQRShape;
    QRBand3: TQRBand;
    QRDBText3: TQRDBText;
    QRMemo1: TQRMemo;
    QRImage1: TQRImage;
    QRImage2: TQRImage;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRDBText10: TQRDBText;
    QRDBText11: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText14: TQRDBText;
    QRDBText15: TQRDBText;
    QRImage3: TQRImage;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRBand4: TQRBand;
    QRSysData1: TQRSysData;
    QRSysData2: TQRSysData;
    QRShape2: TQRShape;
    QRLabel3: TQRLabel;
    QRImage4: TQRImage;
    {$ENDIF}
    procedure _PROC_005338D0(Sender : TObject);
    {$IFDEF FPC}
    /// Creates an owned LazReport builder for a caller-provided dataset.
    function CreateUnit15ListReport(ADataSet: TDataSet): TUnit15ListReport;
    {$ENDIF}
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form15: TSingleColumnA4ReportVariantForm;
  GlobalVar_0061DF14: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC} {$R *.LFM}  {$ELSE} {$R *.DFM}  {$ENDIF} 

procedure TSingleColumnA4ReportVariantForm._PROC_005338D0(Sender : TObject);
begin
  Dec(GlobalVar_0061DF14);
end;

{$IFDEF FPC}
function TSingleColumnA4ReportVariantForm.CreateUnit15ListReport(
  ADataSet: TDataSet): TUnit15ListReport;
begin
  Result := TUnit15ListReport.Create(Self, ADataSet);
end;
{$ENDIF}

end.
