unit TwoColumnA4ReportForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
  {$IFDEF FPC}, DB, Unit25ListReport{$ELSE}, QuickRpt, QRCtrls{$ENDIF};
type
  TTwoColumnA4ReportForm=class(TForm)
    {$IFNDEF FPC}
    QuickRep1: TQuickRep;
    QRBand1: TQRBand;
    QRLabel1: TQRLabel;
    QRShape1: TQRShape;
    QRBand3: TQRBand;
    QRImage1: TQRImage;
    QRImage2: TQRImage;
    QRDBText10: TQRDBText;
    QRDBText11: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText14: TQRDBText;
    QRDBText15: TQRDBText;
    QRImage3: TQRImage;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRBand4: TQRBand;
    QRSysData1: TQRSysData;
    QRSysData2: TQRSysData;
    QRShape2: TQRShape;
    QRLabel3: TQRLabel;
    {$ENDIF}
    procedure _PROC_0055FDD4(Sender : TObject);
    {$IFDEF FPC}
    /// Creates an owned LazReport builder for a caller-provided dataset.
    function CreateUnit25ListReport(ADataSet: TDataSet): TUnit25ListReport;
    {$ENDIF}
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form25: TTwoColumnA4ReportForm;
  GlobalVar_0061E0DC: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC}
{$R *.LFM}
{$ELSE}
{$R *.DFM}
{$ENDIF}

procedure TTwoColumnA4ReportForm._PROC_0055FDD4(Sender : TObject);
begin
  Dec(GlobalVar_0061E0DC);
end;

{$IFDEF FPC}
function TTwoColumnA4ReportForm.CreateUnit25ListReport(
  ADataSet: TDataSet): TUnit25ListReport;
begin
  Result := TUnit25ListReport.Create(Self, ADataSet);
end;
{$ENDIF}

end.