unit AboutForm;

interface

uses
   SysUtils, Classes, Graphics, AboutFormMessageServiceIntf,
  Controls, Forms, Dialogs, StdCtrls,ExtCtrls;

type

  { TAboutForm }

  /// Displays application attribution and build information.
  /// The recovered interactions intentionally distinguish hiding on a click
  /// from closing on a mouse press or Escape key.
  TAboutForm=class(TForm)
    Label1: TLabel;
    Image1: TImage;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    Label5: TLabel;
    Label7: TLabel;
    Image2: TImage;
    Label9: TLabel;
    Label10: TLabel;
    Shape1: TShape;
    Label8: TLabel;
    Timer1: TTimer;
    /// Hides the About form after a form click, preserving the form instance.
    /// <param name="Sender">The form that received the click.</param>
    procedure FormClick(Sender : TObject);
    /// Closes the About form when the Escape key is pressed.
    /// Other keys leave the form open.
    /// <param name="Sender">The focused control or form forwarding the key.</param>
    /// <param name="Key">Virtual key code; Escape is $1B.</param>
    /// <param name="Shift">Modifier keys held with the virtual key.</param>
    procedure FormKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState);
    /// Closes the About form on any mouse-button press received by the form.
    /// The recovered handler does not inspect Button, Shift, X, or Y.
    /// <param name="Sender">The form receiving the mouse-down event.</param>
    /// <param name="Button">Mouse button; ignored by the recovered handler.</param>
    /// <param name="Shift">Modifier keys; ignored by the recovered handler.</param>
    /// <param name="X">Horizontal event coordinate; ignored by the recovered handler.</param>
    /// <param name="Y">Vertical event coordinate; ignored by the recovered handler.</param>
    procedure FormMouseDown(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    /// Closes the About form when invoked.
    /// The retained DFM/LFM resources do not bind this method to Timer1.OnTimer.
    procedure Timer1Timer(Sender : TObject);
    /// Updates the copyright and file-date captions when the form is activated.
    /// <param name="Sender">The form being activated.</param>
    procedure FormActivate(Sender : TObject);
    /// Requests an immediate repaint of the About form after it is shown.
    /// <param name="Sender">The form that has just been shown.</param>
    procedure FormShow(Sender : TObject);
    /// Captures the global form's client dimensions and local file dates.
    /// <param name="Sender">The form being created.</param>
    procedure FormCreate(Sender : TObject);
    /// Increments the address-backed counter; resource reachability is unknown.
    procedure _PROC_005C6E80(Sender : TObject);
    /// Decrements the address-backed counter; resource reachability is unknown.
    procedure _PROC_005C6EB0(Sender : TObject);
  private
    FExecutableModificationDate: TDateTime;
    FDatabaseModificationDate: TDateTime;
    FMetadataError: string;
    FMessageService: IAboutFormMessageService;
    function GetMessageService: IAboutFormMessageService;
  public
    /// Injectable notification boundary; assign a test double before activation.
    property MessageService: IAboutFormMessageService read GetMessageService
      write FMessageService;
  end ;

var
  AboutDialog: TAboutForm;
  GlobalVar_02535884: Integer;
  GlobalVar_02535888: Integer;
  GlobalVar_0253588C: Integer;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

uses
  AboutFormMessageService;

{$IFDEF FPC}
{$R *.LFM}
{$ELSE}
{$R *.DFM}
{$ENDIF}

resourcestring
  rsIssueDateCaption = '(Ausgabe vom %s)';
  rsLastModifiedCaption = 'Letzte Bearbeitung am %s';
  rsUnableToReadFileDate = 'Could not read the modification date for "%s".';

const
  ApplicationExecutableFileName = 'AHNWIN51.exe';
  GenealogyDatabaseFileName = 'awd.db';

/// Attempts to read the local file modification date used by the About dialog.
/// <param name="FileName">The file whose last-modified date is displayed.</param>
/// <param name="ModificationDate">Receives the local modification date and time.</param>
/// <returns>True when the file date was read successfully.</returns>
function TryReadFileModificationDate(const FileName: string;
  out ModificationDate: TDateTime): Boolean;
var
  fileModificationValue: LongInt;
begin
  fileModificationValue := FileAge(FileName);
  Result := fileModificationValue <> -1;
  if Result then
    ModificationDate := FileDateToDateTime(fileModificationValue);
end;

function TAboutForm.GetMessageService: IAboutFormMessageService;
begin
  if FMessageService = nil then
    FMessageService := TAboutFormMessageService.Create;
  Result := FMessageService;
end;

procedure TAboutForm.FormClick(Sender : TObject);
begin
  Hide;
end;

procedure TAboutForm.FormMouseDown(Sender: TObject; Button: TMouseButton;
  Shift: TShiftState; X, Y: Integer);

begin
  Close;
end;

procedure TAboutForm.Timer1Timer(Sender : TObject);
begin
  Close;
end;

procedure TAboutForm.FormKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState
  );
begin
  if Key = $1B then
    Close;
end;

procedure TAboutForm.FormActivate(Sender : TObject);
begin
  Label2.Caption := '© 1998-2014';
  if FMetadataError <> '' then
  begin
    MessageService.ShowError(FMetadataError);
    Exit;
  end;

  Label8.Caption := Format(rsIssueDateCaption, [
    DateToStr(FExecutableModificationDate)]);
  Label9.Caption := Format(rsLastModifiedCaption, [
    DateToStr(FDatabaseModificationDate)]);
end;

procedure TAboutForm.FormShow(Sender : TObject);
begin
  Refresh;
end;

procedure TAboutForm.FormCreate(Sender : TObject);
begin
  GlobalVar_02535884 := AboutDialog.ClientWidth;
  GlobalVar_02535888 := AboutDialog.ClientHeight;

  if not TryReadFileModificationDate(ApplicationExecutableFileName,
    FExecutableModificationDate) then
  begin
    FMetadataError := Format(rsUnableToReadFileDate,
      [ApplicationExecutableFileName]);
    Exit;
  end;

  if not TryReadFileModificationDate(GenealogyDatabaseFileName,
    FDatabaseModificationDate) then
    FMetadataError := Format(rsUnableToReadFileDate,
      [GenealogyDatabaseFileName]);
end;

procedure TAboutForm._PROC_005C6E80(Sender : TObject);
begin
  Inc(GlobalVar_0253588C);
end;

procedure TAboutForm._PROC_005C6EB0(Sender : TObject);
begin
  Dec(GlobalVar_0253588C);
end;

end.
