unit AncestorChartOptionsForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons, ExtCtrls, Spin;
type
  TAncestorChartOptionsForm=class(TForm)
    CheckBox1: TCheckBox;
    CheckBox2: TCheckBox;
    CheckBox3: TCheckBox;
    CheckBox4: TCheckBox;
    CheckBox5: TCheckBox;
    CheckBox6: TCheckBox;
    CheckBox7: TCheckBox;
    CheckBox8: TCheckBox;
    Label1: TLabel;
    Label2: TLabel;
    Panel1: TPanel;
    RadioButton1: TRadioButton;
    RadioButton2: TRadioButton;
    SpinEdit1: TSpinEdit;
    SpinEdit2: TSpinEdit;
    SpeedButton1: TSpeedButton;
    SpeedButton2: TSpeedButton;
    procedure FormShow(Sender : TObject);
    procedure RadioButton1Click(Sender : TObject);
    procedure RadioButton2Click(Sender : TObject);
    procedure SpeedButton2Click(Sender : TObject);
    procedure SpeedButton1Click(Sender : TObject);
    procedure _PROC_00562BB1(Sender : TObject);
    procedure _PROC_00562BE0(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form12: TAncestorChartOptionsForm;
  GlobalVar_02535948: LongInt;
  GlobalVar_0061E100: LongInt;
  GlobalVar_0061E2BC: LongInt;
  GlobalVar_0061E2C0: LongInt;
  GlobalVar_0061E2C4: LongInt;
  GlobalVar_0061E2C8: LongInt;
  GlobalVar_0061E2CC: LongInt;
  GlobalVar_0061E2D0: LongInt;
  GlobalVar_0061E2D4: LongInt;
  GlobalVar_0061E2D8: LongInt;
  GlobalVar_0253592C: string;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

uses
  Unit13;

{$IFDEF FPC} {$R *.LFM}  {$ELSE} {$R *.DFM}  {$ENDIF}

procedure TAncestorChartOptionsForm.FormShow(Sender : TObject);
begin
  GlobalVar_0061E2BC := 0;
  GlobalVar_0061E2C0 := 0;
  GlobalVar_0061E2C4 := 0;
  GlobalVar_0061E2C8 := 0;
  GlobalVar_0061E2CC := 0;
  GlobalVar_0061E2D0 := 0;
  GlobalVar_0061E2D4 := 0;
  GlobalVar_0061E2D8 := 0;

  CheckBox1.Visible := True;
  CheckBox8.Visible := False;
  CheckBox2.Visible := True;
  Label2.Visible := True;
  SpinEdit2.Visible := True;

  if Pos('Nachgr', GlobalVar_0253592C) > 0 then
  begin
    CheckBox2.Visible := False;
    Label2.Visible := False;
    SpinEdit2.Visible := False;
  end;

  ActiveControl := SpinEdit1;
end;

procedure TAncestorChartOptionsForm.RadioButton1Click(Sender : TObject);
begin
  CheckBox1.Checked := True;
  CheckBox2.Checked := True;
  CheckBox3.Checked := True;
  CheckBox4.Checked := True;
  CheckBox5.Checked := True;
  CheckBox6.Checked := True;
  CheckBox7.Checked := True;
  CheckBox8.Checked := True;
end;

procedure TAncestorChartOptionsForm.RadioButton2Click(Sender : TObject);
begin
  CheckBox1.Checked := False;
  CheckBox2.Checked := False;
  CheckBox3.Checked := False;
  CheckBox4.Checked := False;
  CheckBox5.Checked := False;
  CheckBox6.Checked := False;
  CheckBox7.Checked := False;
  CheckBox8.Checked := False;
end;

procedure TAncestorChartOptionsForm.SpeedButton2Click(Sender : TObject);
begin
  GlobalVar_02535948 := 1;
  Form12.ModalResult := mrCancel;
end;

procedure TAncestorChartOptionsForm.SpeedButton1Click(Sender : TObject);
begin
  if CheckBox1.Checked then
    GlobalVar_0061E2BC := 1;
  if CheckBox2.Checked then
    GlobalVar_0061E2C0 := 1;
  if CheckBox3.Checked then
    GlobalVar_0061E2C4 := 1;
  if CheckBox4.Checked then
    GlobalVar_0061E2C8 := 1;
  if CheckBox5.Checked then
    GlobalVar_0061E2CC := 1;
  if CheckBox6.Checked then
    GlobalVar_0061E2D0 := 1;
  if CheckBox7.Checked then
    GlobalVar_0061E2D4 := 1;
  if CheckBox8.Checked then
    GlobalVar_0061E2D8 := 1;

  if GlobalVar_0253592C = 'Vorgr1' then
  begin
    try
      if SpinEdit1.Value < 15 then
      begin
        Form13.Caption := 'Vorfahren-Grafik I';
        Form13.Show;
        Form12.ModalResult := mrCancel;
      end
      else
        ShowMessage('Maximal 14 Generationen möglich');
    except
    end;
  end;

  if GlobalVar_0253592C = 'Vorgr2' then
  begin
    try
      if SpinEdit1.Value < 15 then
      begin
        Form13.Caption := 'Vorfahren-Grafik II';
        Form13.Show;
        Form12.ModalResult := mrCancel;
      end
      else
        ShowMessage('Maximal 14 Generationen möglich');
    except
    end;
  end;

  if GlobalVar_0253592C = 'Nachgr1' then
  begin
    Form13.Caption := 'Nachfahren-Grafik I';
    Form13.Show;
    Form13.Button2.Click;
    Form12.ModalResult := mrCancel;
  end;

  if GlobalVar_0253592C = 'Nachgr2' then
  begin
    Form13.Caption := 'Nachfahren-Grafik II';
    Form13.Show;
    Form12.ModalResult := mrCancel;
  end;

end;

procedure TAncestorChartOptionsForm._PROC_00562BB1(Sender : TObject);
begin
  Inc(GlobalVar_0061E100);
end;

procedure TAncestorChartOptionsForm._PROC_00562BE0(Sender : TObject);
begin
  Dec(GlobalVar_0061E100);
end;

end.
