unit FokoAbbreviationsForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls;
type
  TFokoAbbreviationsForm=class(TForm)
    Memo1: TMemo;
    procedure FormShow(Sender : TObject);
    procedure _PROC_0053A185(Sender : TObject);
    procedure _PROC_0053A1B4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form38: TFokoAbbreviationsForm;
  GlobalVar_0061DFA8: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFokoAbbreviationsForm.FormShow(Sender : TObject);
var
  abbreviationFile: TextFile;
  fileName: string;
  line: string;
begin
  fileName := ExtractFilePath(ParamStr(0)) + 'foko.abk';
  AssignFile(abbreviationFile, fileName);
  Reset(abbreviationFile);
  Memo1.Clear;
  while not Eof(abbreviationFile) do
  begin
    ReadLn(abbreviationFile, line);
    Memo1.Lines.Add(line);
  end;
  CloseFile(abbreviationFile);
end;

procedure TFokoAbbreviationsForm._PROC_0053A185(Sender : TObject);
begin
  Inc(GlobalVar_0061DFA8);
end;

procedure TFokoAbbreviationsForm._PROC_0053A1B4(Sender : TObject);
begin
  Dec(GlobalVar_0061DFA8);
end;

end.