unit FrenchRepublicanCalendarForm;

interface

uses
  LCLType, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, Buttons;
type
  TFrenchRepublicanCalendarForm=class(TForm)
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    Label5: TLabel;
    Shape1: TShape;
    ComboBox1: TComboBox;
    ComboBox2: TComboBox;
    ComboBox3: TComboBox;
    Edit1: TEdit;
    BitBtn1: TBitBtn;
    procedure berechnen;
    procedure FormCreate(Sender : TObject);
    procedure Button1Click(Sender : TObject);
    procedure ComboBox1Change(Sender : TObject);
    procedure ComboBox2Change(Sender : TObject);
    procedure ComboBox3Change(Sender : TObject);
    procedure BitBtn1Click(Sender : TObject);
    procedure FormKeyDown(Sender: TObject; var key: Word; Shift: TShiftState);
    procedure _PROC_005CF32C(Sender : TObject);
    procedure _PROC_005CF35C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form7: TFrenchRepublicanCalendarForm;
  GlobalVar_025358F4: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC} {$R *.LFM}       {$ELSE} {$R *.DFM}       {$ENDIF}

procedure TFrenchRepublicanCalendarForm.berechnen;
var
  republicanYear: string;
  republicanDay: string;
  baseDate: TDateTime;
  formattedDate: string;
  gregorianYear: Integer;
  invalidComplementaryDay: Boolean;
begin
  if (Length(ComboBox1.Text) = 0) or (Length(ComboBox2.Text) = 0) or
    (Length(ComboBox3.Text) = 0) then
    Exit;

  baseDate := 0;
  case ComboBox2.ItemIndex of
    0: baseDate := StrToDate('22.09.1792');
    1: baseDate := StrToDate('22.10.1792');
    2: baseDate := StrToDate('21.11.1792');
    3: baseDate := StrToDate('21.12.1792');
    4: baseDate := StrToDate('20.01.1793');
    5: baseDate := StrToDate('19.02.1793');
    6: baseDate := StrToDate('21.03.1793');
    7: baseDate := StrToDate('20.04.1793');
    8: baseDate := StrToDate('20.05.1793');
    9: baseDate := StrToDate('19.06.1793');
    10: baseDate := StrToDate('19.07.1793');
    11: baseDate := StrToDate('18.08.1793');
  end;

  republicanYear := Trim(ComboBox3.Text);
  if (republicanYear <> 'I') and (republicanYear <> 'II') and
    (republicanYear <> 'III') and (republicanYear <> 'IV') and
    (republicanYear <> 'VI') and (republicanYear <> 'VII') then
    baseDate := baseDate + 1;
  if republicanYear <> 'XII' then
    baseDate := baseDate + 1;

  republicanDay := Trim(ComboBox1.Text);
  invalidComplementaryDay := False;
  if ComboBox1.ItemIndex < 30 then
    baseDate := baseDate + StrToInt(republicanDay) - 1
  else if (republicanDay > '30') and (republicanDay <= 'jrev') then
  begin
    if (Trim(ComboBox2.Text) = 'Fructidor') and
      (ComboBox3.ItemIndex in [2, 6, 10]) then
      baseDate := baseDate + ComboBox1.ItemIndex
    else
      invalidComplementaryDay := True;
  end;

  if invalidComplementaryDay then
  begin
    ShowMessage('Diesen Tag gibt es nicht.');
    Edit1.Text := '';
    Exit;
  end;

  formattedDate := FormatDateTime('dd.mm.yyyy', baseDate);
  gregorianYear := StrToInt(Copy(formattedDate, 7, 4)) +
    ComboBox3.ItemIndex;
  formattedDate := Copy(formattedDate, 1, 6) + IntToStr(gregorianYear);
  baseDate := StrToDate(formattedDate);

  if baseDate > StrToDate('31.12.1805') then
  begin
    Application.MessageBox(
      'Der Revolutionskalender endete am 31.12.1805.',
      'Aus war''s ...', 0);
    Edit1.Text := '';
    Exit;
  end;

  Edit1.Text := FormatDateTime('dd.mm.yyyy', baseDate);
end;

procedure TFrenchRepublicanCalendarForm.FormCreate(Sender : TObject);
begin
  if Screen.Width > 640 then
    if Screen.Height > 480 then
      ScaleBy(Screen.Width, 640);
end;

procedure TFrenchRepublicanCalendarForm.Button1Click(Sender : TObject);
begin
  Close;
end;

procedure TFrenchRepublicanCalendarForm.ComboBox1Change(Sender : TObject);
begin
  if Length(ComboBox1.Text) > 0 then
    berechnen;
end;

procedure TFrenchRepublicanCalendarForm.ComboBox2Change(Sender : TObject);
begin
  if Length(ComboBox2.Text) > 0 then
    berechnen;
end;

procedure TFrenchRepublicanCalendarForm.ComboBox3Change(Sender : TObject);
begin
  if Length(ComboBox3.Text) > 0 then
    berechnen;
end;

procedure TFrenchRepublicanCalendarForm.BitBtn1Click(Sender : TObject);
begin
  Form7.Close;
end;

procedure TFrenchRepublicanCalendarForm.FormKeyDown(Sender : TObject;var key:Word;Shift:TShiftState);
begin
  if key = VK_ESCAPE then
    Close;
end;

procedure TFrenchRepublicanCalendarForm._PROC_005CF32C(Sender : TObject);
begin
  Inc(GlobalVar_025358F4);
end;

procedure TFrenchRepublicanCalendarForm._PROC_005CF35C(Sender : TObject);
begin
  Dec(GlobalVar_025358F4);
end;

end.
