unit frm_About;

interface

uses
   SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls,ExtCtrls;

type

  { TForm9 }

  TForm9=class(TForm)
    Label1: TLabel;
    Image1: TImage;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    Label5: TLabel;
    Label7: TLabel;
    Image2: TImage;
    Label9: TLabel;
    Label10: TLabel;
    Shape1: TShape;
    Label8: TLabel;
    Timer1: TTimer;
    procedure FormClick(Sender : TObject);
    procedure FormKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState);
    procedure FormMouseDown(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure Timer1Timer(Sender : TObject);
    procedure FormActivate(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure _PROC_005C6E80(Sender : TObject);
    procedure _PROC_005C6EB0(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form9: TForm9;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC}
{$R *.LFM}
{$ELSE}
{$R *.DFM}
{$ENDIF}

procedure TForm9.FormClick(Sender : TObject);
begin
(*
005C6CFC   A180585302             mov     eax, dword ptr [$02535880]

* Reference to: Forms.TCustomForm.Hide(TCustomForm);
|
005C6D01   E82E2FEAFF             call    00469C34
005C6D06   C3                     ret

*)
   Hide;
end;

procedure TForm9.FormMouseDown(Sender: TObject; Button: TMouseButton;
  Shift: TShiftState; X, Y: Integer);

begin
(*
005C6D08   55                     push    ebp
005C6D09   8BEC                   mov     ebp, esp
005C6D0B   A180585302             mov     eax, dword ptr [$02535880]

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
005C6D10   E83B2AEAFF             call    00469750
005C6D15   5D                     pop     ebp
005C6D16   C20C00                 ret     $000C

*)
   Close;
end;

procedure TForm9.Timer1Timer(Sender : TObject);
begin
(*
005C6D1C   A180585302             mov     eax, dword ptr [$02535880]

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
005C6D21   E82A2AEAFF             call    00469750
005C6D26   C3                     ret

*)
   Close;
end;

procedure TForm9.FormKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState
  );
begin
(*
005C6D28   55                     push    ebp
005C6D29   8BEC                   mov     ebp, esp
005C6D2B   6683391B               cmp     word ptr [ecx], +$1B
005C6D2F   750A                   jnz     005C6D3B
005C6D31   A180585302             mov     eax, dword ptr [$02535880]

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
005C6D36   E8152AEAFF             call    00469750
005C6D3B   5D                     pop     ebp
005C6D3C   C20400                 ret     $0004

*)
   if key = $1b then
      Close;
end;

procedure TForm9.FormActivate(Sender : TObject);
begin
(*
005C6D40   55                     push    ebp
005C6D41   8BEC                   mov     ebp, esp
005C6D43   33C9                   xor     ecx, ecx
005C6D45   51                     push    ecx
005C6D46   51                     push    ecx
005C6D47   51                     push    ecx
005C6D48   51                     push    ecx
005C6D49   53                     push    ebx
005C6D4A   8BD8                   mov     ebx, eax
005C6D4C   33C0                   xor     eax, eax
005C6D4E   55                     push    ebp

* Possible String Reference to: 'éØÖãÿëë[‹å]Ã'
|
005C6D4F   68EF6D5C00             push    $005C6DEF

***** TRY
|
005C6D54   64FF30                 push    dword ptr fs:[eax]
005C6D57   648920                 mov     fs:[eax], esp

* Possible String Reference to: '© 1998-2014'
|
005C6D5A   BA046E5C00             mov     edx, $005C6E04

* Reference to control TForm9.Label2 : TLabel
|
005C6D5F   8B83F8020000           mov     eax, [ebx+$02F8] *)
(*
* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
005C6D65   E8CA5CE8FF             call    0044CA34*)
   Label2.Caption:='© 1998-2014';
(*
* Possible String Reference to: '(Ausgabe vom '
|
005C6D6A   68186E5C00             push    $005C6E18

* Reference to pointer to GlobalVar_02535924
|
005C6D6F   A180CA6100             mov     eax, dword ptr [$0061CA80]
005C6D74   FF7004                 push    dword ptr [eax+$04]
005C6D77   FF30                   push    dword ptr [eax]
005C6D79   8D45F8                 lea     eax, [ebp-$08]

* Reference to: Unit_00408494.Proc_0040C84C
|
005C6D7C   E8CB5AE4FF             call    0040C84C
005C6D81   FF75F8                 push    dword ptr [ebp-$08]
005C6D84   68306E5C00             push    $005C6E30
005C6D89   8D45FC                 lea     eax, [ebp-$04]
005C6D8C   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00404EE0
|
005C6D91   E84AE1E3FF             call    00404EE0
005C6D96   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TForm9.Label8 : TLabel
|
005C6D99   8B831C030000           mov     eax, [ebx+$031C]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
005C6D9F   E8905CE8FF             call    0044CA34*)
   Label8.Caption:='(Ausgabe vom '+'...)';
(*
* Reference to pointer to GlobalVar_0253591C
|
005C6DA4   A1BCCC6100             mov     eax, dword ptr [$0061CCBC]

005C6DA9   FF7004                 push    dword ptr [eax+$04]
005C6DAC   FF30                   push    dword ptr [eax]
005C6DAE   8D45F0                 lea     eax, [ebp-$10]

* Reference to: Unit_00408494.Proc_0040C84C
|
005C6DB1   E8965AE4FF             call    0040C84C

005C6DB6   8B4DF0                 mov     ecx, [ebp-$10]
005C6DB9   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'Letzte Bearbeitung am '
|
005C6DBC   BA3C6E5C00             mov     edx, $005C6E3C

* Reference to: System.@LStrCat3;
|
005C6DC1   E8A6E0E3FF             call    00404E6C
005C6DC6   8B55F4                 mov     edx, [ebp-$0C]

* Reference to control TForm9.Label9 : TLabel
|
005C6DC9   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
005C6DCF   E8605CE8FF             call    0044CA34  *)
   Label9.Caption:='Letzte Bearbeitung am ';
(*
end;

005C6DD4   33C0                   xor     eax, eax
005C6DD6   5A                     pop     edx
005C6DD7   59                     pop     ecx
005C6DD8   59                     pop     ecx
005C6DD9   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
005C6DDC   68F66D5C00             push    $005C6DF6
005C6DE1   8D45F0                 lea     eax, [ebp-$10]
005C6DE4   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
005C6DE9   E89EDDE3FF             call    00404B8C
005C6DEE   C3                     ret


* Reference to: System.@HandleFinally;
|
005C6DEF   E9D8D6E3FF             jmp     004044CC
005C6DF4   EBEB                   jmp     005C6DE1

****** END
|
005C6DF6   5B                     pop     ebx
005C6DF7   8BE5                   mov     esp, ebp
005C6DF9   5D                     pop     ebp
005C6DFA   C3                     ret

*)
end;

procedure TForm9.FormShow(Sender : TObject);
begin
(*
005C6E54   A180585302             mov     eax, dword ptr [$02535880]

* Reference to: Controls.TControl.Refresh(TControl);
|
005C6E59   E82A61E8FF             call    0044CF88
005C6E5E   C3                     ret

*)
   Invalidate;
end;

procedure TForm9.FormCreate(Sender : TObject);
begin
(*
005C6E60   A180585302             mov     eax, dword ptr [$02535880]

* Reference to: Controls.TControl.GetClientWidth(TControl):Integer;
|
005C6E65   E89E55E8FF             call    0044C408

* Reference to GlobalVar_02535884
|
005C6E6A   A384585302             mov     dword ptr [$02535884], eax
005C6E6F   A180585302             mov     eax, dword ptr [$02535880]

* Reference to: Controls.TControl.GetClientHeight(TControl):Integer;
|
005C6E74   E8D355E8FF             call    0044C44C

* Reference to GlobalVar_02535888
|
005C6E79   A388585302             mov     dword ptr [$02535888], eax
005C6E7E   C3                     ret

*)
end;

procedure TForm9._PROC_005C6E80(Sender : TObject);
begin
(*
005C6E80   55                     push    ebp
005C6E81   8BEC                   mov     ebp, esp
005C6E83   33C0                   xor     eax, eax
005C6E85   55                     push    ebp
005C6E86   68A56E5C00             push    $005C6EA5

***** TRY
|
005C6E8B   64FF30                 push    dword ptr fs:[eax]
005C6E8E   648920                 mov     fs:[eax], esp

005C6E91   FF058C585302           inc     dword ptr [$0253588C]
005C6E97   33C0                   xor     eax, eax
005C6E99   5A                     pop     edx
005C6E9A   59                     pop     ecx
005C6E9B   59                     pop     ecx
005C6E9C   648910                 mov     fs:[eax], edx

****** FINALLY
|
005C6E9F   68AC6E5C00             push    $005C6EAC
005C6EA4   C3                     ret


* Reference to: System.@HandleFinally;
|
005C6EA5   E922D6E3FF             jmp     004044CC
005C6EAA   EBF8                   jmp     005C6EA4

****** END
|
005C6EAC   5D                     pop     ebp
005C6EAD   C3                     ret

*)
end;

procedure TForm9._PROC_005C6EB0(Sender : TObject);
begin
(*
005C6EB0   832D8C58530201         sub     dword ptr [$0253588C], +$01
005C6EB7   C3                     ret

*)
end;

end.
