unit GenealogyListOptionsForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, Buttons;
type
  TGenealogyListOptionsForm=class(TForm)
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    Panel1: TPanel;
    CheckBox2: TCheckBox;
    CheckBox1: TCheckBox;
    CheckBox3: TCheckBox;
    CheckBox4: TCheckBox;
    CheckBox5: TCheckBox;
    CheckBox6: TCheckBox;
    CheckBox12: TCheckBox;
    CheckBox13: TCheckBox;
    CheckBox14: TCheckBox;
    CheckBox15: TCheckBox;
    CheckBox16: TCheckBox;
    Panel2: TPanel;
    CheckBox7: TCheckBox;
    CheckBox8: TCheckBox;
    CheckBox11: TCheckBox;
    Panel3: TPanel;
    CheckBox9: TCheckBox;
    CheckBox10: TCheckBox;
    procedure CheckBox9Click(Sender : TObject);
    procedure CheckBox10Click(Sender : TObject);
    procedure BitBtn1Click(Sender : TObject);
    procedure BitBtn2Click(Sender : TObject);
    procedure _PROC_00563108(Sender : TObject);
    procedure _PROC_00563138(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form31: TGenealogyListOptionsForm;
  GlobalVar_0061E108: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TGenealogyListOptionsForm.CheckBox9Click(Sender : TObject);
begin
  CheckBox1.Checked := True;
  CheckBox2.Checked := True;
  CheckBox3.Checked := True;
  CheckBox4.Checked := True;
  CheckBox5.Checked := True;
  CheckBox6.Checked := True;
  CheckBox7.Checked := True;
  CheckBox8.Checked := True;
  CheckBox9.Checked := True;
  CheckBox11.Checked := True;
  CheckBox12.Checked := True;
  CheckBox13.Checked := True;
  CheckBox14.Checked := True;
  CheckBox15.Checked := True;
  CheckBox16.Checked := True;
  CheckBox10.Checked := False;
end;

procedure TGenealogyListOptionsForm.CheckBox10Click(Sender : TObject);
begin
  CheckBox1.Checked := False;
  CheckBox2.Checked := False;
  CheckBox3.Checked := False;
  CheckBox4.Checked := False;
  CheckBox5.Checked := False;
  CheckBox6.Checked := False;
  CheckBox7.Checked := False;
  CheckBox8.Checked := False;
  CheckBox9.Checked := False;
  CheckBox11.Checked := False;
  CheckBox12.Checked := False;
  CheckBox13.Checked := False;
  CheckBox14.Checked := False;
  CheckBox15.Checked := False;
  CheckBox16.Checked := False;
  CheckBox10.Checked := False;
end;

procedure TGenealogyListOptionsForm.BitBtn1Click(Sender : TObject);
begin
  Form31.Hide;
end;

procedure TGenealogyListOptionsForm.BitBtn2Click(Sender : TObject);
begin
  Form31.Close;
end;

procedure TGenealogyListOptionsForm._PROC_00563108(Sender : TObject);
begin
  Inc(GlobalVar_0061E108);
end;

procedure TGenealogyListOptionsForm._PROC_00563138(Sender : TObject);
begin
  Dec(GlobalVar_0061E108);
end;

end.