object Form31: TGenealogyListOptionsForm
  Left = 192
  Top = 114
  BorderStyle = bsSingle
  Caption = 'Form31'
  ClientHeight = 303
  ClientWidth = 427
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
  object BitBtn1: TBitBtn
    Left = 120
    Top = 262
    Width = 84
    Height = 26
    Caption = 'Fertig'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    Kind = bkOK
  end
  object BitBtn2: TBitBtn
    Left = 224
    Top = 262
    Width = 94
    Height = 26
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    Kind = bkAbort
  end
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 235
    Height = 249
    TabOrder = 2
    object CheckBox2: TCheckBox
      Left = 24
      Top = 53
      Width = 97
      Height = 17
      Caption = 'Quellen'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object CheckBox1: TCheckBox
      Left = 24
      Top = 21
      Width = 97
      Height = 17
      Caption = 'IDs'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object CheckBox3: TCheckBox
      Left = 24
      Top = 85
      Width = 97
      Height = 17
      Caption = 'Text(e)'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object CheckBox4: TCheckBox
      Left = 24
      Top = 117
      Width = 97
      Height = 17
      Caption = 'Beruf'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
    end
    object CheckBox5: TCheckBox
      Left = 24
      Top = 181
      Width = 97
      Height = 17
      Caption = 'Bekenntnis'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object CheckBox6: TCheckBox
      Left = 24
      Top = 213
      Width = 111
      Height = 17
      Caption = 'Todesursachen'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object CheckBox12: TCheckBox
      Left = 24
      Top = 149
      Width = 97
      Height = 17
      Caption = 'Hausname'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
    end
    object CheckBox13: TCheckBox
      Left = 123
      Top = 21
      Width = 97
      Height = 17
      Caption = 'Taufpaten'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
    end
    object CheckBox14: TCheckBox
      Left = 123
      Top = 53
      Width = 97
      Height = 17
      Caption = 'Trauzeugen'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 8
    end
    object CheckBox15: TCheckBox
      Left = 123
      Top = 85
      Width = 97
      Height = 17
      Caption = 'Lebensort(e)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
    end
    object CheckBox16: TCheckBox
      Left = 123
      Top = 117
      Width = 97
      Height = 17
      Caption = 'Bürgerort(e)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 10
    end
  end
  object Panel2: TPanel
    Left = 236
    Top = 0
    Width = 191
    Height = 127
    TabOrder = 3
    object CheckBox7: TCheckBox
      Left = 22
      Top = 24
      Width = 162
      Height = 17
      Caption = 'alphabetische Liste'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object CheckBox8: TCheckBox
      Left = 22
      Top = 56
      Width = 161
      Height = 17
      Caption = 'Ahnenschwund berücks.'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object CheckBox11: TCheckBox
      Left = 22
      Top = 88
      Width = 163
      Height = 17
      Caption = 'nichtehel.Nachkommen'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
  end
  object Panel3: TPanel
    Left = 236
    Top = 128
    Width = 191
    Height = 121
    TabOrder = 4
    object CheckBox9: TCheckBox
      Left = 24
      Top = 21
      Width = 152
      Height = 17
      Caption = 'alle markieren'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object CheckBox10: TCheckBox
      Left = 24
      Top = 53
      Width = 152
      Height = 17
      Caption = 'alle löschen'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
  end
end
