unit GregorianCalendar;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, Buttons, Grids,
  GregorianCalendarViewModelIntf;

// Gregorian calendar form.

type

  { The original executable identifies this class as TForm6. }

  /// Legacy calendar view with its display state supplied through a ViewModel interface.
  /// The form is responsible for rendering controls and presenting navigation feedback;
  /// GregorianCalendarViewModel owns the accepted year and calendar cell values.
  TGregorianCalendarForm=class(TForm)
    Shape1: TShape;
    StringGrid1: TStringGrid;
    StringGrid2: TStringGrid;
    StringGrid3: TStringGrid;
    edtYear: TEdit;
    btnFollowYear: TButton;
    btnPrevYear: TButton;
    btnOK: TBitBtn;
    edtJanuary: TEdit;
    edtFebruary: TEdit;
    edtMarch: TEdit;
    edtApril: TEdit;
    edtMay: TEdit;
    edtJune: TEdit;
    edtJuly: TEdit;
    edtAugust: TEdit;
    Edit10: TEdit;
    Edit11: TEdit;
    Edit12: TEdit;
    Edit13: TEdit;
    btnPrintKalender: TSpeedButton;
    /// Applies the recovered 640-by-800 scaling and 18-by-23 grid metrics on larger screens.
    /// <param name="Sender">Form-create event source; retained for the LCL event signature.</param>
    procedure FormCreate(Sender : TObject);
    /// Clears all cells in each of the three calendar grids before a redraw.
    /// The full-grid clear also removes stale Sundays and week columns when years change.
    /// <param name="Sender">Event source; retained for compatibility with the original handler.</param>
    procedure gridleeren(Sender : TObject);
    /// Synchronizes the year edit with the ViewModel and renders all three month panels.
    /// Each panel displays four months; weekdays occupy rows and column zero contains labels.
    /// <param name="Sender">Event source for form display or year navigation.</param>
    /// <exception cref="EInvalidOpException">No ViewModel has been injected.</exception>
    /// <exception cref="EConvertError">The entered year is not a supported Gregorian year.</exception>
    procedure Kal(Sender : TObject);
    /// Renders the initially selected year when the form becomes visible.
    /// <param name="Sender">Form-show event source.</param>
    procedure FormShow(Sender : TObject);
    /// Advances the displayed year by one when it is below 2499.
    /// Displays the recovered warning and restores the last accepted year at the upper bound.
    /// <param name="Sender">Button-click event source.</param>
    procedure btnFollowYearClick(Sender : TObject);
    /// Moves the displayed year back by one when it is above 1582.
    /// Displays the recovered warning and restores the last accepted year at the lower bound.
    /// <param name="Sender">Button-click event source.</param>
    procedure btnPrevYearClick(Sender : TObject);
    /// Recalculates the calendar after a valid four-character year edit.
    /// Invalid-length or non-numeric intermediate text is ignored; out-of-range years warn
    /// and restore the last accepted ViewModel year.
    /// <param name="Sender">Edit-change event source.</param>
    procedure edtYearChange(Sender : TObject);
    procedure btnOKClick(Sender : TObject);
    procedure FormKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState);
    procedure edtYearKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState);
    procedure FormActivate(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure btnPrintKalenderClick(Sender : TObject);
    procedure _PROC_005CE618(Sender : TObject);
    procedure _PROC_005CE648(Sender : TObject);
  private
    FViewModel: IGregorianCalendarViewModel;
    procedure PrintCalendar(Sender: TObject);
    /// Returns the injected ViewModel or raises rather than silently skipping rendering.
    /// <exception cref="EInvalidOpException">No ViewModel has been injected.</exception>
    function RequireViewModel: IGregorianCalendarViewModel;
    { Private declarations }
  public
    /// View-facing contract; the concrete implementation is supplied by the composition root.
    property ViewModel: IGregorianCalendarViewModel read FViewModel write FViewModel;
    { Public declarations }
  end ;

var
  GregorianCalendarForm: TGregorianCalendarForm;
  GlobalVar_025358EC: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

uses
  GregorianCalendarPrintCompatibilityError,
  GregorianCalendarPrintWorkflow;

{$IFDEF FPC} {$R *.LFM} {$ELSE} {$R *.DFM} {$ENDIF}

function TGregorianCalendarForm.RequireViewModel: IGregorianCalendarViewModel;
begin
  if FViewModel = nil then
    raise EInvalidOpException.Create('Gregorian calendar view model was not injected.');
  Result := FViewModel;
end;

procedure TGregorianCalendarForm.FormCreate(Sender : TObject);
begin
  if (Screen.Width <= 640) or (Screen.Height <= 480) then
    Exit;

  ScaleBy(640, 800);

  StringGrid1.DefaultRowHeight := Round(18.0);
  StringGrid1.DefaultColWidth := Round(23.0);
  StringGrid2.DefaultRowHeight := Round(18.0);
  StringGrid2.DefaultColWidth := Round(23.0);
  StringGrid3.DefaultRowHeight := Round(18.0);
  StringGrid3.DefaultColWidth := Round(23.0);
end;

procedure TGregorianCalendarForm.gridleeren(Sender : TObject);
var
  row, column: Integer;
begin
  for row := 0 to StringGrid1.RowCount - 1 do
    for column := 0 to StringGrid1.ColCount - 1 do
    begin
      StringGrid1.Cells[column, row] := '';
      StringGrid2.Cells[column, row] := '';
      StringGrid3.Cells[column, row] := '';
    end;
end;

procedure TGregorianCalendarForm.Kal(Sender : TObject);
var
  grids: array[0..2] of TStringGrid;
  gridIndex, column, row: Integer;
  dayText: string;
  calendarViewModel: IGregorianCalendarViewModel;
begin
  calendarViewModel := RequireViewModel;
  if edtYear.Text = '' then
    edtYear.Text := IntToStr(calendarViewModel.Year);

  calendarViewModel.Year := StrToInt(edtYear.Text);
  gridleeren(Sender);

  grids[0] := StringGrid1;
  grids[1] := StringGrid2;
  grids[2] := StringGrid3;
  for gridIndex := Low(grids) to High(grids) do
  begin
    for row := 0 to grids[gridIndex].RowCount - 1 do
      grids[gridIndex].Cells[0, row] := calendarViewModel.GetWeekdayLabel(row);

    for column := 0 to grids[gridIndex].ColCount - 1 do
      for row := 0 to grids[gridIndex].RowCount - 1 do
      begin
        dayText := calendarViewModel.GetDayCellText(gridIndex, column, row);
        if dayText <> '' then
          grids[gridIndex].Cells[column, row] :=
            dayText;
      end;
  end;
end;
procedure TGregorianCalendarForm.FormShow(Sender : TObject);
begin

  Kal(Sender);
end;

procedure TGregorianCalendarForm.btnFollowYearClick(Sender : TObject);
var
  currentYear: Longint;
begin

  currentYear := StrToInt(edtYear.Text);
  if currentYear < 2499 then
  begin
    edtYear.Text := IntToStr(currentYear + 1);
    Kal(Sender);
  end
  else
  begin
    MessageDlg('Nein, nein ...', 'Das Jahr muss kleiner als 2500 sein.',
      mtWarning, [mbOK], 0);
    edtYear.Text := IntToStr(RequireViewModel.Year);
  end;
end;

procedure TGregorianCalendarForm.btnPrevYearClick(Sender : TObject);
var
  currentYear: Longint;
begin

  currentYear := StrToInt(edtYear.Text);
  if currentYear > 1581 then
  begin
    edtYear.Text := IntToStr(currentYear - 1);
    Kal(Sender);
  end
  else
  begin
    MessageDlg('Nein, nein ...', 'Das Jahr muss größer als 1581 sein.',
      mtWarning, [mbOK], 0);
    edtYear.Text := IntToStr(RequireViewModel.Year);
  end;
end;

procedure TGregorianCalendarForm.edtYearChange(Sender : TObject);
var
  lYear: Longint;
begin
  if Length(edtYear.Text) <> 4 then
    Exit;

  if not TryStrToInt(edtYear.Text, lYear) then
    Exit;

  if (lYear > 1581) and (lYear < 2500) then
  begin
    Kal(Sender);
  end
  else
  begin
    if lYear <= 1581 then
    MessageDlg('Nein, nein ...', 'Das Jahr muss größer als 1581 sein.',
      mtWarning, [mbOK], 0);

    if lYear >= 2500 then
      MessageDlg('Nein, nein ...', 'Das Jahr muss kleiner als 2500 sein.',
        mtWarning, [mbOK], 0);

    edtYear.Text := IntToStr(RequireViewModel.Year);
  end;
end;

procedure TGregorianCalendarForm.btnOKClick(Sender : TObject);
begin

   Close;
end;

procedure TGregorianCalendarForm.FormKeyDown(Sender: TObject;var Key: Word; Shift: TShiftState);
begin

   if Key = VK_ESCAPE then
     Close;
end;

procedure TGregorianCalendarForm.edtYearKeyDown(Sender : TObject;var Key: Word; Shift: TShiftState);
begin

  if Key = VK_ESCAPE then
     Close;
end;

procedure TGregorianCalendarForm.FormActivate(Sender : TObject);
begin

end;

procedure TGregorianCalendarForm.FormClose(Sender : TObject);
begin

   ModalResult:= 0;
end;

procedure TGregorianCalendarForm.btnPrintKalenderClick(Sender : TObject);
begin
{$IFDEF FPC}
  raise EGregorianCalendarPrintUnsupported.Create('Form.Print');
{$ELSE}
  RunGregorianCalendarPrintWorkflow(Self, btnFollowYear, btnPrevYear,
    btnOK, btnPrintKalender, PrintCalendar);
{$ENDIF}
end;

procedure TGregorianCalendarForm.PrintCalendar(Sender: TObject);
begin
{$IFDEF FPC}
  raise EGregorianCalendarPrintUnsupported.Create('Form.Print');
{$ELSE}
  Print;
{$ENDIF}
end;

procedure TGregorianCalendarForm._PROC_005CE618(Sender : TObject);
begin
  Inc(GlobalVar_025358EC);
end;

procedure TGregorianCalendarForm._PROC_005CE648(Sender : TObject);
begin
  Dec(GlobalVar_025358EC);
end;

end.
