unit OrtsfamilienbuchOptionsForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, DB,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, Buttons;
  
type
  TOrtsfamilienbuchOptionsForm=class(TForm)
    Label1: TLabel;
    Label2: TLabel;
    ListBox1: TListBox;
    ListBox2: TListBox;
    ListBox3: TListBox;
    ListBox4: TListBox;
    Button2: TButton;
    Button3: TButton;
    Button4: TButton;
    Button5: TButton;
    Button6: TButton;
    Button7: TButton;
    Panel1: TPanel;
    Shape1: TShape;
    Panel2: TPanel;
    Button9: TButton;
    CheckBox4: TCheckBox;
    CheckBox5: TCheckBox;
    CheckBox6: TCheckBox;
    CheckBox7: TCheckBox;
    CheckBox8: TCheckBox;
    CheckBox9: TCheckBox;
    Panel3: TPanel;
    RadioButton4: TRadioButton;
    RadioButton5: TRadioButton;
    SpeedButton1: TSpeedButton;
    SpeedButton2: TSpeedButton;
    CheckBox2: TCheckBox;
    CheckBox10: TCheckBox;
    ListBox5: TListBox;
    ListBox6: TListBox;
    Button1: TSpeedButton;
    Button8: TButton;
    Button10: TButton;
    Label4: TLabel;
    CheckBox1: TCheckBox;
    Panel4: TPanel;
    Label3: TLabel;
    RadioButton1: TRadioButton;
    RadioButton2: TRadioButton;
    RadioButton3: TRadioButton;
    CheckBox14: TCheckBox;
    CheckBox16: TCheckBox;
    CheckBox15: TCheckBox;
    CheckBox17: TCheckBox;
    Panel5: TPanel;
    Label5: TLabel;
    CheckBox18: TCheckBox;
    CheckBox3: TCheckBox;
    CheckBox11: TCheckBox;
    procedure Button9Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure listanz;
    procedure Button2Click(Sender : TObject);
    procedure Button4Click(Sender : TObject);
    procedure Button6Click(Sender : TObject);
    procedure Button3Click(Sender : TObject);
    procedure Button5Click(Sender : TObject);
    procedure Button7Click(Sender : TObject);
    procedure ListBox1DblClick(Sender : TObject);
    procedure ListBox2DblClick(Sender : TObject);
    procedure ListBox3DblClick(Sender : TObject);
    procedure ListBox4DblClick(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure RadioButton4Click(Sender : TObject);
    procedure RadioButton5Click(Sender : TObject);
    procedure SpeedButton1Click(Sender : TObject);
    procedure SpeedButton2Click(Sender : TObject);
    procedure CheckBox17Click(Sender : TObject);
    procedure CheckBox18Click(Sender : TObject);
    procedure Button1Click(Sender : TObject);
    procedure Button8Click(Sender : TObject);
    procedure Button10Click(Sender : TObject);
    procedure ListBox5DblClick(Sender : TObject);
    procedure _PROC_0055FA85(Sender : TObject);
    procedure _PROC_0055FAC8(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form24: TOrtsfamilienbuchOptionsForm;
  GlobalVar_02535B50: string;
  GlobalVar_0061E0D4: LongInt;
  GlobalVar_0061E0D0: string;
  GlobalVar_0061E0CC: string;
  GlobalVar_025353E0: LongInt;
  GlobalVar_025353E4: LongInt;
  GlobalVar_025353E8: LongInt;
  GlobalVar_025353EC: LongInt;
  GlobalVar_025353F0: LongInt;
  GlobalVar_025353F4: LongInt;
  GlobalVar_025353F8: LongInt;
  GlobalVar_025353FC: LongInt;
  GlobalVar_02535400: LongInt;
  GlobalVar_02535404: LongInt;
  GlobalVar_02535408: LongInt;
  GlobalVar_0253540C: LongInt;
  GlobalVar_02535410: LongInt;
  GlobalVar_02535414: LongInt;
  GlobalVar_02535418: LongInt;
  GlobalVar_0253541C: LongInt;
  GlobalVar_02535420: LongInt;
  GlobalVar_02535424: LongInt;

procedure RefreshFieldLists(FieldListForm: TOrtsfamilienbuchOptionsForm;
  NameDataSet: TDataSet; NameField: TField;
  LocationDataSet: TDataSet; LocationField: TField;
  HouseNameDataSet: TDataSet; HouseNameField: TField);

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC}
{$R *.LFM}
{$ELSE}
{$R *.DFM}
{$ENDIF}

uses
  GenealogyDataModule, frmAhnenWinMain;

procedure AppendPositiveFieldValues(DataSet: TDataSet; ValueField: TField;
  Items: TStrings);
begin
  DataSet.Open;
  DataSet.First;
  while not DataSet.EOF do
  begin
    if ValueField.AsInteger > 0 then
      Items.Add(ValueField.AsString);
    DataSet.Next;
  end;
end;

procedure RefreshFieldLists(FieldListForm: TOrtsfamilienbuchOptionsForm;
  NameDataSet: TDataSet; NameField: TField;
  LocationDataSet: TDataSet; LocationField: TField;
  HouseNameDataSet: TDataSet; HouseNameField: TField);
begin
  FieldListForm.ListBox1.Clear;
  FieldListForm.ListBox2.Clear;
  FieldListForm.ListBox3.Clear;
  FieldListForm.ListBox4.Clear;
  FieldListForm.ListBox5.Clear;
  FieldListForm.ListBox6.Clear;

  AppendPositiveFieldValues(NameDataSet, NameField,
    FieldListForm.ListBox1.Items);
  AppendPositiveFieldValues(LocationDataSet, LocationField,
    FieldListForm.ListBox2.Items);
  AppendPositiveFieldValues(HouseNameDataSet, HouseNameField,
    FieldListForm.ListBox5.Items);
end;

procedure TOrtsfamilienbuchOptionsForm.Button9Click(Sender : TObject);
begin
  Form1.listen_akt;
  listanz;
end;

procedure TOrtsfamilienbuchOptionsForm.FormShow(Sender : TObject);
begin
  listanz;
  RadioButton1.Enabled := True;
  RadioButton3.Enabled := True;
  ActiveControl := ListBox1;
end;

procedure TOrtsfamilienbuchOptionsForm.listanz;
begin
  RefreshFieldLists(Self,
    DataModule2.Table12, DataModule2.Table12Name,
    DataModule2.Table13, DataModule2.Table13Ort,
    DataModule2.Table37, DataModule2.Table37Hofname);
end;

procedure TOrtsfamilienbuchOptionsForm.Button2Click(Sender : TObject);
begin
  Form24.ListBox3.Items.Add(
    Form24.ListBox1.Items[Form24.ListBox1.ItemIndex]);
end;

procedure TOrtsfamilienbuchOptionsForm.Button4Click(Sender : TObject);
begin
  Form24.ListBox3.Items.Delete(Form24.ListBox3.ItemIndex);
end;

procedure TOrtsfamilienbuchOptionsForm.Button6Click(Sender : TObject);
begin
  Form24.ListBox3.Clear;
end;

procedure TOrtsfamilienbuchOptionsForm.Button3Click(Sender : TObject);
begin
  Form24.ListBox4.Items.Add(
    Form24.ListBox2.Items[Form24.ListBox2.ItemIndex]);
end;

procedure TOrtsfamilienbuchOptionsForm.Button5Click(Sender : TObject);
begin
  Form24.ListBox4.Items.Delete(Form24.ListBox4.ItemIndex);
end;

procedure TOrtsfamilienbuchOptionsForm.Button7Click(Sender : TObject);
begin
  Form24.ListBox4.Clear;
end;

procedure TOrtsfamilienbuchOptionsForm.ListBox1DblClick(Sender : TObject);
begin
  Form24.ListBox3.Items.Add(
    Form24.ListBox1.Items[Form24.ListBox1.ItemIndex]);
end;

procedure TOrtsfamilienbuchOptionsForm.ListBox2DblClick(Sender : TObject);
begin
  Form24.ListBox4.Items.Add(
    Form24.ListBox2.Items[Form24.ListBox2.ItemIndex]);
end;

procedure TOrtsfamilienbuchOptionsForm.ListBox3DblClick(Sender : TObject);
begin
  Form24.ListBox3.Items.Delete(Form24.ListBox3.ItemIndex);
end;

procedure TOrtsfamilienbuchOptionsForm.ListBox4DblClick(Sender : TObject);
begin
  Form24.ListBox4.Items.Delete(Form24.ListBox4.ItemIndex);
end;

procedure TOrtsfamilienbuchOptionsForm.FormClose(Sender : TObject);
var
  index: Integer;
begin
  GlobalVar_0061E0CC := '';
  for index := 0 to ListBox3.Items.Count - 1 do
    GlobalVar_0061E0CC := GlobalVar_0061E0CC + ListBox3.Items[index] + '%';

  GlobalVar_0061E0D0 := '';
  for index := 0 to ListBox4.Items.Count - 1 do
    GlobalVar_0061E0D0 := GlobalVar_0061E0D0 + ListBox4.Items[index] + '%';

  GlobalVar_025353E0 := 0;
  GlobalVar_025353E4 := 0;
  GlobalVar_025353E8 := 0;
  GlobalVar_025353EC := 0;
  GlobalVar_025353F0 := 0;
  GlobalVar_025353F4 := 0;
  GlobalVar_025353F8 := 0;
  GlobalVar_025353FC := 0;
  GlobalVar_02535400 := 0;
  GlobalVar_02535404 := 0;
  GlobalVar_02535408 := 0;
  GlobalVar_0253540C := 0;
  GlobalVar_02535410 := 0;
  GlobalVar_02535414 := 0;
  GlobalVar_02535418 := 0;
  GlobalVar_0253541C := 0;
  GlobalVar_02535420 := 0;
  GlobalVar_02535424 := 0;

  if RadioButton1.Checked then
    GlobalVar_025353E0 := 1;
  if RadioButton2.Checked then
    GlobalVar_025353E4 := 1;
  if RadioButton3.Checked then
    GlobalVar_025353E8 := 1;
  if CheckBox1.Checked then
    GlobalVar_0253541C := 1;
  if CheckBox2.Checked then
    GlobalVar_02535408 := 1;
  if CheckBox3.Checked then
    GlobalVar_02535420 := 1;
  if CheckBox4.Checked then
    GlobalVar_025353EC := 1;
  if CheckBox5.Checked then
    GlobalVar_025353F0 := 1;
  if CheckBox6.Checked then
    GlobalVar_025353F4 := 1;
  if CheckBox7.Checked then
    GlobalVar_025353F8 := 1;
  if CheckBox8.Checked then
    GlobalVar_025353FC := 1;
  if CheckBox9.Checked then
    GlobalVar_02535400 := 1;
  if CheckBox10.Checked then
    GlobalVar_02535404 := 1;
  if CheckBox11.Checked then
    GlobalVar_02535424 := 1;
  if CheckBox14.Checked then
    GlobalVar_0253540C := 1;
  if CheckBox16.Checked then
    GlobalVar_02535410 := 1;
  if CheckBox17.Checked then
    GlobalVar_02535414 := 1;
  if CheckBox18.Checked then
    GlobalVar_02535418 := 1;
end;

procedure TOrtsfamilienbuchOptionsForm.RadioButton4Click(Sender : TObject);
begin
  CheckBox1.Checked := True;
  CheckBox2.Checked := True;
  CheckBox3.Checked := True;
  CheckBox4.Checked := True;
  CheckBox5.Checked := True;
  CheckBox6.Checked := True;
  CheckBox7.Checked := True;
  CheckBox8.Checked := True;
  CheckBox9.Checked := True;
  CheckBox10.Checked := True;
  CheckBox11.Checked := True;
end;

procedure TOrtsfamilienbuchOptionsForm.RadioButton5Click(Sender : TObject);
begin
  CheckBox1.Checked := False;
  CheckBox2.Checked := False;
  CheckBox3.Checked := False;
  CheckBox4.Checked := False;
  CheckBox5.Checked := False;
  CheckBox6.Checked := False;
  CheckBox7.Checked := False;
  CheckBox8.Checked := False;
  CheckBox9.Checked := False;
  CheckBox10.Checked := False;
  CheckBox11.Checked := False;
end;

procedure TOrtsfamilienbuchOptionsForm.SpeedButton1Click(Sender : TObject);
var
  confirmed: Boolean;
begin
  confirmed := ListBox3.Items.Count > 0;
  if not confirmed then
    confirmed := ListBox4.Items.Count > 0;
  if not confirmed then
    confirmed := ListBox6.Items.Count > 0;
  if not confirmed then
    confirmed := Application.MessageBox(
      'Weder Name noch Ort noch Hofname ausgewählt.Trotzdem weiter ?',
      'OFB-Druck', MB_YESNO) = IDYES;

  if confirmed then
  begin
    GlobalVar_02535B50 := 'butt1';
    Form24.ModalResult := mrCancel;
  end;
end;

procedure TOrtsfamilienbuchOptionsForm.SpeedButton2Click(Sender : TObject);
begin
  GlobalVar_02535B50 := 'butt8';
  Form24.ModalResult := mrCancel;
end;

procedure TOrtsfamilienbuchOptionsForm.CheckBox17Click(Sender : TObject);
begin
  if not CheckBox17.Checked then
    CheckBox18.Checked := False;
end;

procedure TOrtsfamilienbuchOptionsForm.CheckBox18Click(Sender : TObject);
begin
  if not CheckBox17.Checked then
    CheckBox18.Checked := False;
end;

procedure TOrtsfamilienbuchOptionsForm.Button1Click(Sender : TObject);
begin
  Form24.ListBox6.Items.Add(
    Form24.ListBox5.Items[Form24.ListBox5.ItemIndex]);
  if Form24.ListBox6.Items.Count > 0 then
  begin
    RadioButton1.Enabled := False;
    RadioButton2.Checked := True;
    RadioButton3.Enabled := False;
  end;
end;

procedure TOrtsfamilienbuchOptionsForm.Button8Click(Sender : TObject);
begin
  Form24.ListBox6.Items.Delete(Form24.ListBox6.ItemIndex);
  if Form24.ListBox6.Items.Count = 0 then
  begin
    RadioButton1.Enabled := True;
    RadioButton3.Enabled := True;
  end;
end;

procedure TOrtsfamilienbuchOptionsForm.Button10Click(Sender : TObject);
begin
  Form24.ListBox6.Clear;
  RadioButton1.Enabled := True;
  RadioButton3.Enabled := True;
end;

procedure TOrtsfamilienbuchOptionsForm.ListBox5DblClick(Sender : TObject);
begin
  if Form24.ListBox6.Items.Count > 0 then
    ShowMessage(
      'Es kann nur 1 Hofname ausgewählt werden, sonst gibt es Durcheinander.')
  else
  begin
    Form24.ListBox6.Items.Add(
      Form24.ListBox5.Items[Form24.ListBox5.ItemIndex]);
    if Form24.ListBox6.Items.Count > 0 then
    begin
      RadioButton1.Enabled := False;
      RadioButton2.Checked := True;
      RadioButton3.Enabled := False;
    end;
  end;
end;

procedure TOrtsfamilienbuchOptionsForm._PROC_0055FA85(Sender : TObject);
begin
  Inc(GlobalVar_0061E0D4);
  if GlobalVar_0061E0D4 = 0 then
  begin
    GlobalVar_0061E0D0 := '';
    GlobalVar_0061E0CC := '';
  end;
end;

procedure TOrtsfamilienbuchOptionsForm._PROC_0055FAC8(Sender : TObject);
begin
  Dec(GlobalVar_0061E0D4);
end;

end.
