unit PersonEntryChoiceForm;

interface

uses
  Classes, Controls, ExtCtrls, Forms, StdCtrls;

const
  { Values written to the form's ModalResult field by the recovered handlers. }
  PersonEntryChoiceCreateNew = mrOk;
  PersonEntryChoiceSelectExisting = mrCancel;

type
  { Presents create-new, select-existing, or return choices for a person entry. }
  TPersonEntryChoiceForm = class(TForm)
    ChoicePanel: TPanel;
    CreateNewRadioButton: TRadioButton;
    SelectExistingRadioButton: TRadioButton;
    CancelRadioButton: TRadioButton;
    /// Returns the recovered value used for the create-new option.
    procedure CreateNewRadioButtonClick(Sender: TObject);
    /// Returns the recovered value used for selecting an existing person.
    procedure SelectExistingRadioButtonClick(Sender: TObject);
    /// Closes the choice dialog without applying a parent relationship.
    procedure CancelRadioButtonClick(Sender: TObject);
    /// Starts each activation with all three choices unchecked.
    procedure FormActivate(Sender: TObject);
    /// Increments the address-backed state cell; no resource binding is known.
    procedure _PROC_005C6A20(Sender : TObject);
    /// Decrements the address-backed state cell; no resource binding is known.
    procedure _PROC_005C6A50(Sender : TObject);
  end;

var
  PersonEntryChoiceDialog: TPersonEntryChoiceForm;
  GlobalVar_0253587C: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC}
{$R *.lfm}
{$ELSE}
{$R *.dfm}
{$ENDIF}

procedure TPersonEntryChoiceForm.CreateNewRadioButtonClick(Sender: TObject);
begin
  ModalResult := PersonEntryChoiceCreateNew;
end;

procedure TPersonEntryChoiceForm.SelectExistingRadioButtonClick(
  Sender: TObject);
begin
  ModalResult := PersonEntryChoiceSelectExisting;
end;

procedure TPersonEntryChoiceForm.CancelRadioButtonClick(Sender: TObject);
begin
  Close;
end;

procedure TPersonEntryChoiceForm.FormActivate(Sender: TObject);
begin
  CreateNewRadioButton.Checked := False;
  SelectExistingRadioButton.Checked := False;
  CancelRadioButton.Checked := False;
end;

procedure TPersonEntryChoiceForm._PROC_005C6A20(Sender : TObject);
begin
  Inc(GlobalVar_0253587C);
end;

procedure TPersonEntryChoiceForm._PROC_005C6A50(Sender : TObject);
begin
  Dec(GlobalVar_0253587C);
end;

end.