unit PersonEntryChoiceForm;

interface

uses
  Classes, Controls, ExtCtrls, Forms, StdCtrls;

const
  { Values written to the form's ModalResult field by the recovered handlers. }
  PersonEntryChoiceCreateNew = mrOk;
  PersonEntryChoiceSelectExisting = mrCancel;

type
  { Presents create-new, select-existing, or return choices for a person entry. }
  TPersonEntryChoiceForm = class(TForm)
    ChoicePanel: TPanel;
    CreateNewRadioButton: TRadioButton;
    SelectExistingRadioButton: TRadioButton;
    CancelRadioButton: TRadioButton;
    /// Returns the recovered value used for the create-new option.
    procedure CreateNewRadioButtonClick(Sender: TObject);
    /// Returns the recovered value used for selecting an existing person.
    procedure SelectExistingRadioButtonClick(Sender: TObject);
    /// Closes the choice dialog without applying a parent relationship.
    procedure CancelRadioButtonClick(Sender: TObject);
    /// Starts each activation with all three choices unchecked.
    procedure FormActivate(Sender: TObject);
    /// UNDER CONSTRUCTION: retain the unbound address-based callback listing.
    procedure _PROC_005C6A20(Sender : TObject);
    /// UNDER CONSTRUCTION: retain the unbound address-based callback listing.
    procedure _PROC_005C6A50(Sender : TObject);
  end;

var
  PersonEntryChoiceDialog: TPersonEntryChoiceForm;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC}
{$R *.lfm}
{$ELSE}
{$R *.dfm}
{$ENDIF}

procedure TPersonEntryChoiceForm.CreateNewRadioButtonClick(Sender: TObject);
begin
  ModalResult := PersonEntryChoiceCreateNew;
end;

procedure TPersonEntryChoiceForm.SelectExistingRadioButtonClick(
  Sender: TObject);
begin
  ModalResult := PersonEntryChoiceSelectExisting;
end;

procedure TPersonEntryChoiceForm.CancelRadioButtonClick(Sender: TObject);
begin
  Close;
end;

procedure TPersonEntryChoiceForm.FormActivate(Sender: TObject);
begin
  CreateNewRadioButton.Checked := False;
  SelectExistingRadioButton.Checked := False;
  CancelRadioButton.Checked := False;
end;

procedure TPersonEntryChoiceForm._PROC_005C6A20(Sender : TObject);
begin
(*
005C6A20   55                     push    ebp
005C6A21   8BEC                   mov     ebp, esp
005C6A23   33C0                   xor     eax, eax
005C6A25   55                     push    ebp
005C6A26   68456A5C00             push    $005C6A45

***** TRY
|
005C6A2B   64FF30                 push    dword ptr fs:[eax]
005C6A2E   648920                 mov     fs:[eax], esp
005C6A31   FF057C585302           inc     dword ptr [$0253587C]
005C6A37   33C0                   xor     eax, eax
005C6A39   5A                     pop     edx
005C6A3A   59                     pop     ecx
005C6A3B   59                     pop     ecx
005C6A3C   648910                 mov     fs:[eax], edx

****** FINALLY
|
005C6A3F   684C6A5C00             push    $005C6A4C
005C6A44   C3                     ret


* Reference to: System.@HandleFinally;
|
005C6A45   E982DAE3FF             jmp     004044CC
005C6A4A   EBF8                   jmp     005C6A44

****** END
|
005C6A4C   5D                     pop     ebp
005C6A4D   C3                     ret

*)
end;

procedure TPersonEntryChoiceForm._PROC_005C6A50(Sender : TObject);
begin
(*
005C6A50   832D7C58530201         sub     dword ptr [$0253587C], +$01
005C6A57   C3                     ret

*)
end;

end.