unit PersonComparisonOptionsForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons, ExtCtrls;
type
  TPersonComparisonOptionsForm=class(TForm)
    Label1: TLabel;
    Label2: TLabel;
    Shape1: TShape;
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    BitBtn3: TBitBtn;
    BitBtn4: TBitBtn;
    CheckBox1: TCheckBox;
    CheckBox2: TCheckBox;
    CheckBox3: TCheckBox;
    CheckBox4: TCheckBox;
    CheckBox5: TCheckBox;
    CheckBox6: TCheckBox;
    CheckBox7: TCheckBox;
    CheckBox8: TCheckBox;
    CheckBox9: TCheckBox;
    Shape2: TShape;
    RadioButton1: TRadioButton;
    RadioButton2: TRadioButton;
    CheckBox10: TCheckBox;
    procedure BitBtn4Click(Sender : TObject);
    procedure BitBtn3Click(Sender : TObject);
    procedure RadioButton1Click(Sender : TObject);
    procedure RadioButton2Click(Sender : TObject);
    procedure _PROC_005CFAA4(Sender : TObject);
    procedure _PROC_005CFAD4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form35: TPersonComparisonOptionsForm;
  GlobalVar_02535B90: LongInt;
  GlobalVar_02535B98: string;
  GlobalVar_02535B8C: LongInt;
  GlobalVar_02535B88: LongInt;
  GlobalVar_02535B68: LongInt;
  GlobalVar_02535B6C: LongInt;
  GlobalVar_02535B70: LongInt;
  GlobalVar_02535B74: LongInt;
  GlobalVar_02535B78: LongInt;
  GlobalVar_02535B7C: LongInt;
  GlobalVar_02535B80: LongInt;
  GlobalVar_02535B84: LongInt;
  GlobalVar_025358FC: LongInt;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TPersonComparisonOptionsForm.BitBtn4Click(Sender : TObject);
begin
  GlobalVar_02535B90 := 0;
  Form35.ModalResult := mrCancel;
end;

procedure TPersonComparisonOptionsForm.BitBtn3Click(Sender : TObject);
begin
  GlobalVar_02535B98 := '';
  GlobalVar_02535B90 := 1;
  if CheckBox10.Checked then
  begin
    GlobalVar_02535B8C := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', ID';
  end;
  if CheckBox9.Checked then
  begin
    GlobalVar_02535B88 := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', Beruf';
  end;
  if CheckBox1.Checked then
  begin
    GlobalVar_02535B68 := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', Geb.Jahr';
  end;
  if CheckBox2.Checked then
  begin
    GlobalVar_02535B6C := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', Geb.Ort';
  end;
  if CheckBox3.Checked then
  begin
    GlobalVar_02535B70 := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', Taufjahr';
  end;
  if CheckBox4.Checked then
  begin
    GlobalVar_02535B74 := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', Taufort';
  end;
  if CheckBox5.Checked then
  begin
    GlobalVar_02535B78 := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', St.Jahr';
  end;
  if CheckBox6.Checked then
  begin
    GlobalVar_02535B7C := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', St.Ort';
  end;
  if CheckBox7.Checked then
  begin
    GlobalVar_02535B80 := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', Best.Jahr';
  end;
  if CheckBox8.Checked then
  begin
    GlobalVar_02535B84 := 1;
    GlobalVar_02535B98 := GlobalVar_02535B98 + ', Best.Ort';
  end;
  Form35.ModalResult := mrCancel;
end;

procedure TPersonComparisonOptionsForm.RadioButton1Click(Sender : TObject);
begin
  CheckBox1.Checked := True;
  CheckBox2.Checked := True;
  CheckBox3.Checked := True;
  CheckBox4.Checked := True;
  CheckBox5.Checked := True;
  CheckBox6.Checked := True;
  CheckBox7.Checked := True;
  CheckBox8.Checked := True;
  CheckBox9.Checked := True;
  CheckBox10.Checked := True;
  RadioButton1.Checked := False;
  RadioButton2.Checked := False;
end;

procedure TPersonComparisonOptionsForm.RadioButton2Click(Sender : TObject);
begin
  CheckBox1.Checked := False;
  CheckBox2.Checked := False;
  CheckBox3.Checked := False;
  CheckBox4.Checked := False;
  CheckBox5.Checked := False;
  CheckBox6.Checked := False;
  CheckBox7.Checked := False;
  CheckBox8.Checked := False;
  CheckBox9.Checked := False;
  CheckBox10.Checked := False;
  RadioButton1.Checked := False;
  RadioButton2.Checked := False;
end;

procedure TPersonComparisonOptionsForm._PROC_005CFAA4(Sender : TObject);
begin
  Inc(GlobalVar_025358FC);
end;

procedure TPersonComparisonOptionsForm._PROC_005CFAD4(Sender : TObject);
begin
  Dec(GlobalVar_025358FC);
end;

end.