unit Traduction;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils;

procedure LoadFromFile(aLanguage:string;out Success:boolean);overload;
procedure LoadFromFile(aLanguage:string);overload;

var Items:TStrings;

resourcestring
  rsMenuHistoryCaption = '&%d- %s (%d)';
  SAreYouSureToQuit	= 'Are you syre you want to quit STEMMA?';
  SUnableToConnectToDB 	= 'Couldn''t connect to MySQL database %s.';
  SConfirmation		= 'Confirmation';
  SDatabaseName 	= 'Database name';
  SEnterDBName		= 'Enter the database name to be created';
  STitle		= 'Title';
  SSuffix		= 'Suffix';
  SFamilyName		= 'Name';
  SGivenName		= 'First name';

implementation


procedure LoadFromFile(aLanguage: string; out Success: boolean); overload;
begin
  Success:=false;
  if FileExists(aLanguage) then
    begin
      items.LoadFromFile(aLanguage);
      Success:=true;
    end;
end;

procedure LoadFromFile(aLanguage: string);
var success:boolean;
begin
  LoadFromFile(aLanguage,Success);
end;


initialization
  items:=TStringList.Create;
  Items.Add(SAreYouSureToQuit);
Items.Add(SConfirmation);
Items.Add(SUnableToConnectToDB);
Items.Add(SDatabaseName);
Items.Add(SEnterDBName);
Items.Add('Database already existing.');
Items.Add('Location of the TMG 4.0d database');
Items.Add('Step 1/12 - Event type importation');
Items.Add('Step 2/12 - Source-repository association importation');
Items.Add('Step 3/12 - Repository importation');
Items.Add('Step 4/12 - Event Importation - Time to completion ');
Items.Add('Step 5/12 - Citation importation - Time to completion ');
Items.Add('Step 6/12 - Individual importation - Time to completion ');
Items.Add('Step 7/12 - Place importation - Time to completion ');
Items.Add('Step 8/12 - Witness importation - Time to completion ');
Items.Add('Step 9/12 - Name importation - Time to completion ');
Items.Add('Step 10/12 - Relation importation - Time to completion ');
Items.Add('Step 11/12 - Source importation - Time to completion ');
Items.Add('Step 12/12 - Exhibits importation - Time to completion ');
Items.Add('Error: STEMMA Database already existing or impossible to open imported database.');
Items.Add('Number of the individual');
Items.Add('Enter the number of the desired individual');
Items.Add('The individual ');
Items.Add(' has not been found.');
Items.Add('Enter the database name to delete');
Items.Add('Enter the database name');
Items.Add('Database not found.');
Items.Add('Are you sure you want to delete repository "');
Items.Add('" ?');
Items.Add('Add a citation');
Items.Add('Add an event');
Items.Add('Are you sure you want to delete citation "');
Items.Add('Are you sure you want to delete witness "');
Items.Add('Add an exhibit');
Items.Add('Text');
Items.Add('Add an individual');
Items.Add('Add a name');
Items.Add(SFamilyName);
Items.Add(SGivenName);
Items.Add(SSuffix);
Items.Add(STitle);
Items.Add('Add a child');
Items.Add('Add a parent');
Items.Add('Add a source');
Items.Add('Are you sure you want to delete the link to the depository "');
Items.Add('Depository modification');
Items.Add('Enter the depository #');
Items.Add('Add a depository');
Items.Add('Add a witness');
Items.Add('B - Birth events');
Items.Add('D - Death events');
Items.Add('M - Union events');
Items.Add('X - Other events');
Items.Add('N - Names');
Items.Add('R - Filiations');
Items.Add('Z - Other relations');
Items.Add('Add an event, name or relation type');
Items.Add('Children');
Items.Add('Are you sure you want to delete the link to the child "');
Items.Add('Events');
Items.Add('Are you sure you want to delete "');
Items.Add('Only the exhibits associated to an individual (type "I") can be modified this way');
Items.Add('Are you sure you want to delete exhibit "');
Items.Add('NO TITLE, NO DESCRIPTION');
Items.Add('image');
Items.Add('Exhibits');
Items.Add('she');
Items.Add('he');
Items.Add('her');
Items.Add('his');
Items.Add('daughter of ');
Items.Add('son of ');
Items.Add(' and ');
Items.Add('TO BE PROGRAMMED');
Items.Add('first');
Items.Add('january');
Items.Add('fébruary');
Items.Add('march');
Items.Add('april');
Items.Add('may');
Items.Add('june');
Items.Add('july');
Items.Add('august');
Items.Add('september');
Items.Add('october');
Items.Add('november');
Items.Add('december');
Items.Add('before the ');
Items.Add('before ');
Items.Add('before a ');
Items.Add(' of the year ');
Items.Add('circa the ');
Items.Add('circa ');
Items.Add('circa a ');
Items.Add('the ');
Items.Add('in ');
Items.Add('a ');
Items.Add('after the ');
Items.Add('after ');
Items.Add('after a ');
Items.Add('between the ');
Items.Add('between ');
Items.Add('between a ');
Items.Add(' and the ');
Items.Add(' and a ');
Items.Add(' or the ');
Items.Add(' or in ');
Items.Add(' or a ');
Items.Add('from ');
Items.Add('from ');
Items.Add('from a ');
Items.Add(' to ');
Items.Add(' to ');
Items.Add(' to a ');
Items.Add('c.');
Items.Add(' or ');
Items.Add('Siblings');
Items.Add('Principal exhibit');
Items.Add('Selected exhibit');
Items.Add('Merge with...');
Items.Add('Enter the place # with "');
Items.Add('" should merge');
Items.Add('Not the same place (');
Items.Add(') vs (');
Items.Add('Error');
Items.Add('Are you sure you want to delete place "');
Items.Add('Names');
Items.Add(') and attributes');
Items.Add('To remove a primary name, select the new primary name.');
Items.Add('Are you sure you want to delete the name "');
Items.Add('Parents');
Items.Add('Are you sure you want to delete the link to the  parent "');
Items.Add('Are you sure you want to delete source "');
Items.Add('Are you sure you want to delete "');
Items.Add('Event');
Items.Add('Witness');
Items.Add('Date');
Items.Add('# Source');
Items.Add('Source');
Items.Add('# Author');
Items.Add('Author');
Items.Add('Select the desired language file');
Items.Add('About');
Items.Add('Version:');
Items.Add('Date:');
Items.Add('by François Marchi');
Items.Add('Ancestors');
Items.Add('Connexion to database');
Items.Add('Close');
Items.Add('User:');
Items.Add('Server:');
Items.Add('Password:');
Items.Add('Ok');
Items.Add('Repositories');
Items.Add('Title');
Items.Add('Description');
Items.Add('Memo');
Items.Add('Individual');
Items.Add('Usage');
Items.Add('Descendants');
Items.Add('Citation modification');
Items.Add('Source:');
Items.Add('Description:');
Items.Add('Quality:');
Items.Add('Cancel');
Items.Add('Event modification');
Items.Add('Type:');
Items.Add('Witnesses:');
Items.Add('(presentation):');
Items.Add('(sort):');
Items.Add('Place:');
Items.Add('Memo:');
Items.Add('Sentence:');
Items.Add('(default)');
Items.Add('Citations:');
Items.Add('Role');
Items.Add('Name');
Items.Add('Q');
Items.Add('Exhibit modification');
Items.Add('Title:');
Items.Add('File:');
Items.Add('Visualise');
Items.Add('Name modification');
Items.Add('Individual:');
Items.Add('Name:');
Items.Add('Type');
Items.Add('Relation modification');
Items.Add('Parent:');
Items.Add('Child:');
Items.Add('Sort date:');
Items.Add('Source modification');
Items.Add('Author:');
Items.Add('Default Quality:');
Items.Add('Repositories:');
Items.Add('Repository');
Items.Add('Witness modification');
Items.Add('Witness:');
Items.Add('Role:');
Items.Add('Result:');
Items.Add('Event type modification');
Items.Add('Child');
Items.Add('Format');
Items.Add('Explorer');
Items.Add('Birth');
Items.Add('Death');
Items.Add('Sibling');
Items.Add('Navigation history');
Items.Add('Places');
Items.Add('Preposition');
Items.Add('Detail');
Items.Add('City');
Items.Add('Region');
Items.Add('State');
Items.Add('Country');
Items.Add('Names and Attributes');
Items.Add('Last modification:');
Items.Add('Parent');
Items.Add('Exhibit display');
Items.Add('Sources');
Items.Add('Author');
Items.Add('Event types');
Items.Add('Phrase');
Items.Add('&Go to');
Items.Add('&Usage');
Items.Add('&Add');
Items.Add('&Modify');
Items.Add('&Delete');
Items.Add('&Witnesses');
Items.Add('&Citations');
Items.Add('Add &title');
Items.Add('Add &first name');
Items.Add('Add &surname');
Items.Add('Add suffi&x');
Items.Add('&Repositories');
Items.Add('&Primary');
Items.Add('Sort by &first name');
Items.Add('Sort by &surname');
Items.Add('Sort by &birth');
Items.Add('Sort by &death');
Items.Add('&Sort');
Items.Add('by &detail');
Items.Add('by &city');
Items.Add('by &region');
Items.Add('by &state');
Items.Add('by countr&y');
Items.Add('&Merge');
Items.Add('by &number');
Items.Add('by &title');
Items.Add('&File');
Items.Add('Conne&xion');
Items.Add('&Create project');
Items.Add('&Open project');
Items.Add('&Import project');
Items.Add('&TMG v. 4.0d');
Items.Add('Delete project');
Items.Add('&Language');
Items.Add('&Quit');
Items.Add('&Edit');
Items.Add('Copy');
Items.Add('Cut');
Items.Add('Paste');
Items.Add('Copy &name');
Items.Add('Copy indi&vidual');
Items.Add('Delete individual');
Items.Add('&Father');
Items.Add('&Mother');
Items.Add('&Broter');
Items.Add('&Sister');
Items.Add('S&on');
Items.Add('&Daughter');
Items.Add('S&pouse');
Items.Add('&Unrelated');
Items.Add('B&irth');
Items.Add('Bap&tism');
Items.Add('D&eath');
Items.Add('Buria&l');
Items.Add('&Navigation');
Items.Add('By &number');
Items.Add('&Previous explorer element');
Items.Add('Ne&xt explorer element');
Items.Add('Complete &history');
Items.Add('&Tools');
Items.Add('&Sources');
Items.Add('&Places');
Items.Add('&Event Types');
Items.Add('&Window');
Items.Add('&Explorer');
Items.Add('&Names and attributes');
Items.Add('E&vents');
Items.Add('&Parents');
Items.Add('E&xhibits');
Items.Add('&Children');
Items.Add('&Siblings');
Items.Add('&Image');
Items.Add('&Ancestors');
Items.Add('&Descendants');
Items.Add('&Help');
Items.Add('&About');
Items.Add('Exhibits:');
Items.Add('" and "');
Items.Add('Do you want to unite "');
Items.Add('There must be at least one witness.');
Items.Add('&Parameters');
Items.Add('&PDF');
Items.Add('Select the location of the PDF viewer');
Items.Add('Executables');
Items.Add('Language translation table');
Items.Add('The deleted person must not be a depot, author of a source, have principal child, parents nor events where another person is a principal witness.');
Items.Add('Copie &event');
Items.Add('Copie Pa&rent');
Items.Add('Copie &Child');
Items.Add('Adding a father to ');
Items.Add('Adding a mother to ');
Items.Add('Adding a brother to ');
Items.Add('Adding a son to ');
Items.Add('Adding a daughter to ');
Items.Add('Selection of the other principal parent');
Items.Add('None for now...');
Items.Add('Adding a spouse to ');
Items.Add('E');
Items.Add('ENGLISH');
Items.Add('&Export project');
Items.Add('&Website');
Items.Add('SITEMAP files creation (1/3)');
Items.Add('Index creation (2/3)');
Items.Add('Database transfer file creation (3/3)');
Items.Add('Directory where to create HTML/PHP files');
Items.Add('Enter the web site server name or address');
Items.Add('Server name');
Items.Add('Enter the website database name');
Items.Add('Database name');
Items.Add('Enter the website MySQL username');
Items.Add('Username');
Items.Add('Enter the username password');
Items.Add('Password');
Items.Add('Database compression');
Items.Add('Repair Birth-Death');
Items.Add('Adding a sister to ');
Items.Add('Removal of orphan records');
Items.Add('Repair names (for sorting)');
Items.Add('Repair relation sort date');
finalization
  freeandnil(Items);
end.

