unit AHW52PasswordDialog;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, AHW52PasswordSessionIntf;

type
  TPasswordDialog=class(TForm)
    GroupBox1: TGroupBox;
    Edit: TEdit;
    AddButton: TButton;
    RemoveButton: TButton;
    RemoveAllButton: TButton;
    OKButton: TButton;
    CancelButton: TButton;
    procedure EditChange(Sender : TObject);
    procedure AddButtonClick(Sender : TObject);
    procedure RemoveButtonClick(Sender : TObject);
    procedure RemoveAllButtonClick(Sender : TObject);
    procedure OKButtonClick(Sender : TObject);
    procedure _PROC_004B147C(Sender : TObject);
    procedure _PROC_004B14B8(Sender : TObject);
  private
    PasswordAdded: Boolean;
    FSession: IAHW52PasswordSession;
    function RequireSession: IAHW52PasswordSession;
  public
    property PasswordSession: IAHW52PasswordSession read FSession
      write FSession;
  end ;

var
  PasswordDialog: TPasswordDialog;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R DBPWDlg.DFM}

procedure TPasswordDialog.EditChange(Sender : TObject);
var
  passwordEntered: Boolean;
begin
  passwordEntered := Edit.Text <> '';
  AddButton.Enabled := passwordEntered;
  RemoveButton.Enabled := passwordEntered;
  OKButton.Enabled := passwordEntered or PasswordAdded;
end;

function TPasswordDialog.RequireSession: IAHW52PasswordSession;
begin
  if FSession = nil then
    raise EInvalidOpException.Create('Password session was not assigned.');
  Result := FSession;
end;

procedure TPasswordDialog.AddButtonClick(Sender : TObject);
begin
  RequireSession.AddPassword(Edit.Text);
  PasswordAdded := True;
  Edit.Clear;
  Edit.SetFocus;
end;

procedure TPasswordDialog.RemoveButtonClick(Sender : TObject);
begin
  RequireSession.RemovePassword(Edit.Text);
  Edit.Clear;
  Edit.SetFocus;
end;

procedure TPasswordDialog.RemoveAllButtonClick(Sender : TObject);
begin
  RequireSession.RemoveAllPasswords;
  Edit.SetFocus;
end;

procedure TPasswordDialog.OKButtonClick(Sender : TObject);
begin
  RequireSession.AddPassword(Edit.Text);
end;

procedure TPasswordDialog._PROC_004B147C(Sender : TObject);
begin
(*
004B147C   55                     push    ebp
004B147D   8BEC                   mov     ebp, esp
004B147F   33C0                   xor     eax, eax
004B1481   55                     push    ebp
004B1482   68AC144B00             push    $004B14AC

***** TRY
|
004B1487   64FF30                 push    dword ptr fs:[eax]
004B148A   648920                 mov     fs:[eax], esp
004B148D   FF0538DD6100           inc     dword ptr [$0061DD38]
004B1493   7509                   jnz     004B149E

* Reference to pointer to GlobalVar_0061DD20
|
004B1495   A13CC26100             mov     eax, dword ptr [$0061C23C]
004B149A   33D2                   xor     edx, edx
004B149C   8910                   mov     [eax], edx
004B149E   33C0                   xor     eax, eax
004B14A0   5A                     pop     edx
004B14A1   59                     pop     ecx
004B14A2   59                     pop     ecx
004B14A3   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Í@'
|
004B14A6   68B3144B00             push    $004B14B3
004B14AB   C3                     ret


* Reference to: System.@HandleFinally;
|
004B14AC   E91B30F5FF             jmp     004044CC
004B14B1   EBF8                   jmp     004B14AB

****** END
|
004B14B3   5D                     pop     ebp
004B14B4   C3                     ret

*)
end;

procedure TPasswordDialog._PROC_004B14B8(Sender : TObject);
begin
(*
004B14B8   832D38DD610001         sub     dword ptr [$0061DD38], +$01
004B14BF   730B                   jnb     004B14CC

* Reference to pointer to GlobalVar_0061DD20
|
004B14C1   A13CC26100             mov     eax, dword ptr [$0061C23C]
004B14C6   C70024124B00           mov     dword ptr [eax], $004B1224
004B14CC   C3                     ret

*)
end;

end.
