unit DBLogDlg;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls;

type
  TLoginDialog=class(TForm)
    Panel: TPanel;
    Bevel: TBevel;
    DatabaseName: TLabel;
    OKButton: TButton;
    CancelButton: TButton;
    Panel1: TPanel;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    Password: TEdit;
    UserName: TEdit;
    procedure FormShow(Sender : TObject);
    procedure _PROC_004B0BF0(Sender : TObject);
    procedure _PROC_004B0D20(Sender : TObject);
    procedure _PROC_004B0F28(Sender : TObject);
    procedure _PROC_004B0F38(Sender : TObject);
    procedure _PROC_004B0F68(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  LoginDialog: TLoginDialog;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TLoginDialog.FormShow(Sender : TObject);
var
  availableWidth: Integer;
begin
  availableWidth := Panel.ClientWidth;
  if availableWidth <= DatabaseName.Left + DatabaseName.Width then
    DatabaseName.Width := availableWidth - DatabaseName.Left - 5;
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TLoginDialog.DatabaseName (TLabel); TLoginDialog.Password (TEdit); TLoginDialog.UserName
    (TEdit); TApplication instance
Framework/API calls: class TLoginDialog; Controls.TControl.GetText(TControl):TCaption;;
    Controls.TControl.SetText(TControl;TCaption);;
    Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);;
    Forms.TCustomForm.SetActiveControl(TCustomForm;TWinControl);; method TEdit.SetEnabled(Boolean);
    method TLoginDialog.ShowModal(); System.TObject.Free(TObject);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TLoginDialog._PROC_004B0BF0(Sender : TObject);
begin
(*
004B0BF0   55                     push    ebp
004B0BF1   8BEC                   mov     ebp, esp
004B0BF3   83C4F0                 add     esp, -$10
004B0BF6   53                     push    ebx
004B0BF7   56                     push    esi
004B0BF8   57                     push    edi
004B0BF9   33DB                   xor     ebx, ebx
004B0BFB   895DF0                 mov     [ebp-$10], ebx
004B0BFE   895DF4                 mov     [ebp-$0C], ebx
004B0C01   8BF9                   mov     edi, ecx
004B0C03   8BDA                   mov     ebx, edx
004B0C05   8BF0                   mov     esi, eax
004B0C07   33C0                   xor     eax, eax
004B0C09   55                     push    ebp
004B0C0A   680C0D4B00             push    $004B0D0C

***** TRY
|
004B0C0F   64FF30                 push    dword ptr fs:[eax]
004B0C12   648920                 mov     fs:[eax], esp

* Reference to TApplication instance
|
004B0C15   8B0D0CC96100           mov     ecx, [$0061C90C]
004B0C1B   8B09                   mov     ecx, [ecx]
004B0C1D   B201                   mov     dl, $01

* Reference to class TLoginDialog
|
004B0C1F   A198084B00             mov     eax, dword ptr [$004B0898]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
004B0C24   E8934AFBFF             call    004656BC
004B0C29   8945F8                 mov     [ebp-$08], eax
004B0C2C   33C0                   xor     eax, eax
004B0C2E   55                     push    ebp
004B0C2F   68EA0C4B00             push    $004B0CEA

***** TRY
|
004B0C34   64FF30                 push    dword ptr fs:[eax]
004B0C37   648920                 mov     fs:[eax], esp
004B0C3A   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.DatabaseName : TLabel
|
004B0C3D   8B80F8020000           mov     eax, [eax+$02F8]
004B0C43   8BD6                   mov     edx, esi

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
004B0C45   E8EABDF9FF             call    0044CA34
004B0C4A   8B13                   mov     edx, [ebx]
004B0C4C   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
004B0C4F   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
004B0C55   E8DABDF9FF             call    0044CA34
004B0C5A   C645FF00               mov     byte ptr [ebp-$01], $00
004B0C5E   807D0800               cmp     byte ptr [ebp+$08], $00
004B0C62   7412                   jz      004B0C76
004B0C64   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
004B0C67   8B8018030000           mov     eax, [eax+$0318]
004B0C6D   33D2                   xor     edx, edx
004B0C6F   8B08                   mov     ecx, [eax]

* Reference to method TEdit.SetEnabled(Boolean)
|
004B0C71   FF5164                 call    dword ptr [ecx+$64]
004B0C74   EB16                   jmp     004B0C8C
004B0C76   833B00                 cmp     dword ptr [ebx], +$00
004B0C79   7511                   jnz     004B0C8C
004B0C7B   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
004B0C7E   8B9018030000           mov     edx, [eax+$0318]
004B0C84   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Forms.TCustomForm.SetActiveControl(TCustomForm;TWinControl);
|
004B0C87   E86471FBFF             call    00467DF0
004B0C8C   8B45F8                 mov     eax, [ebp-$08]
004B0C8F   8B10                   mov     edx, [eax]

* Reference to method TLoginDialog.ShowModal()
|
004B0C91   FF92E8000000           call    dword ptr [edx+$00E8]
004B0C97   48                     dec     eax
004B0C98   753A                   jnz     004B0CD4
004B0C9A   8D55F4                 lea     edx, [ebp-$0C]
004B0C9D   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
004B0CA0   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004B0CA6   E859BDF9FF             call    0044CA04
004B0CAB   8B55F4                 mov     edx, [ebp-$0C]
004B0CAE   8BC3                   mov     eax, ebx

* Reference to: System.@LStrAsg(void;void;void;void);
|
004B0CB0   E8073FF5FF             call    00404BBC
004B0CB5   8D55F0                 lea     edx, [ebp-$10]
004B0CB8   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Password : TEdit
|
004B0CBB   8B8014030000           mov     eax, [eax+$0314]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004B0CC1   E83EBDF9FF             call    0044CA04
004B0CC6   8B55F0                 mov     edx, [ebp-$10]
004B0CC9   8BC7                   mov     eax, edi

* Reference to: System.@LStrAsg(void;void;void;void);
|
004B0CCB   E8EC3EF5FF             call    00404BBC
004B0CD0   C645FF01               mov     byte ptr [ebp-$01], $01
004B0CD4   33C0                   xor     eax, eax
004B0CD6   5A                     pop     edx
004B0CD7   59                     pop     ecx
004B0CD8   59                     pop     ecx
004B0CD9   648910                 mov     fs:[eax], edx

****** FINALLY
|
004B0CDC   68F10C4B00             push    $004B0CF1
004B0CE1   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.TObject.Free(TObject);
|
004B0CE4   E84F30F5FF             call    00403D38
004B0CE9   C3                     ret


* Reference to: System.@HandleFinally;
|
004B0CEA   E9DD37F5FF             jmp     004044CC
004B0CEF   EBF0                   jmp     004B0CE1

****** END
|
004B0CF1   33C0                   xor     eax, eax
004B0CF3   5A                     pop     edx
004B0CF4   59                     pop     ecx
004B0CF5   59                     pop     ecx
004B0CF6   648910                 mov     fs:[eax], edx

****** FINALLY
|
004B0CF9   68130D4B00             push    $004B0D13
004B0CFE   8D45F0                 lea     eax, [ebp-$10]
004B0D01   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
004B0D06   E8813EF5FF             call    00404B8C
004B0D0B   C3                     ret


* Reference to: System.@HandleFinally;
|
004B0D0C   E9BB37F5FF             jmp     004044CC
004B0D11   EBEB                   jmp     004B0CFE

****** END
|
004B0D13   8A45FF                 mov     al, byte ptr [ebp-$01]
004B0D16   5F                     pop     edi
004B0D17   5E                     pop     esi
004B0D18   5B                     pop     ebx
004B0D19   8BE5                   mov     esp, ebp
004B0D1B   5D                     pop     ebp
004B0D1C   C20400                 ret     $0004

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TLoginDialog.Bevel (TBevel); TLoginDialog.CancelButton (TButton);
    TLoginDialog.DatabaseName (TLabel); TLoginDialog.Label3 (TLabel); TLoginDialog.OKButton
    (TButton); TLoginDialog.Panel (TPanel); TLoginDialog.Password (TEdit); TLoginDialog.UserName
    (TEdit); TApplication instance
Framework/API calls: class TLoginDialog; Controls.TControl.GetText(TControl):TCaption;;
    Controls.TControl.SetHeight(TControl;Integer);; Controls.TControl.SetText(TControl;TCaption);;
    Controls.TControl.SetTop(TControl;Integer);; Controls.TControl.SetVisible(TControl;Boolean);;
    Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);;
    Forms.TCustomForm.SetActiveControl(TCustomForm;TWinControl);; method TLoginDialog.ShowModal();
    System.LoadResString(PResStringRec):String;; System.TObject.Free(TObject);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TLoginDialog._PROC_004B0D20(Sender : TObject);
begin
(*
004B0D20   55                     push    ebp
004B0D21   8BEC                   mov     ebp, esp
004B0D23   33C9                   xor     ecx, ecx
004B0D25   51                     push    ecx
004B0D26   51                     push    ecx
004B0D27   51                     push    ecx
004B0D28   51                     push    ecx
004B0D29   51                     push    ecx
004B0D2A   53                     push    ebx
004B0D2B   56                     push    esi
004B0D2C   8BF2                   mov     esi, edx
004B0D2E   8BD8                   mov     ebx, eax
004B0D30   33C0                   xor     eax, eax
004B0D32   55                     push    ebp
004B0D33   68CE0E4B00             push    $004B0ECE

***** TRY
|
004B0D38   64FF30                 push    dword ptr fs:[eax]
004B0D3B   648920                 mov     fs:[eax], esp

* Reference to TApplication instance
|
004B0D3E   8B0D0CC96100           mov     ecx, [$0061C90C]
004B0D44   8B09                   mov     ecx, [ecx]
004B0D46   B201                   mov     dl, $01

* Reference to class TLoginDialog
|
004B0D48   A198084B00             mov     eax, dword ptr [$004B0898]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
004B0D4D   E86A49FBFF             call    004656BC
004B0D52   8945F8                 mov     [ebp-$08], eax
004B0D55   33D2                   xor     edx, edx
004B0D57   55                     push    ebp
004B0D58   68A40E4B00             push    $004B0EA4

***** TRY
|
004B0D5D   64FF32                 push    dword ptr fs:[edx]
004B0D60   648922                 mov     fs:[edx], esp
004B0D63   8D55F4                 lea     edx, [ebp-$0C]
004B0D66   A128C56100             mov     eax, dword ptr [$0061C528]

* Reference to: System.LoadResString(PResStringRec):String;
|
004B0D6B   E86062F5FF             call    00406FD0
004B0D70   8B55F4                 mov     edx, [ebp-$0C]
004B0D73   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
004B0D76   E8B9BCF9FF             call    0044CA34
004B0D7B   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Bevel : TBevel
|
004B0D7E   8B80F4020000           mov     eax, [eax+$02F4]
004B0D84   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
004B0D86   E899BBF9FF             call    0044C924
004B0D8B   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.DatabaseName : TLabel
|
004B0D8E   8B80F8020000           mov     eax, [eax+$02F8]
004B0D94   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
004B0D96   E889BBF9FF             call    0044C924
004B0D9B   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Label3 : TLabel
|
004B0D9E   8B8010030000           mov     eax, [eax+$0310]
004B0DA4   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
004B0DA6   E879BBF9FF             call    0044C924
004B0DAB   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Panel : TPanel
|
004B0DAE   8B80F0020000           mov     eax, [eax+$02F0]

* Reference to field TPanel.Height : Integer
|
004B0DB4   8B504C                 mov     edx, [eax+$4C]
004B0DB7   8B4DF8                 mov     ecx, [ebp-$08]
004B0DBA   8B89F4020000           mov     ecx, [ecx+$02F4]
004B0DC0   2B5144                 sub     edx, dword ptr [ecx+$44]

* Reference to: Controls.TControl.SetHeight(TControl;Integer);
|
004B0DC3   E8F4B3F9FF             call    0044C1BC
004B0DC8   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.OKButton : TButton
|
004B0DCB   8B80FC020000           mov     eax, [eax+$02FC]

* Reference to field TButton.Top : Integer
|
004B0DD1   8B5044                 mov     edx, [eax+$44]
004B0DD4   8B4DF8                 mov     ecx, [ebp-$08]
004B0DD7   8B89F4020000           mov     ecx, [ecx+$02F4]
004B0DDD   2B5144                 sub     edx, dword ptr [ecx+$44]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
004B0DE0   E88BB3F9FF             call    0044C170
004B0DE5   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.CancelButton : TButton
|
004B0DE8   8B8000030000           mov     eax, [eax+$0300]

* Reference to field TButton.Top : Integer
|
004B0DEE   8B5044                 mov     edx, [eax+$44]
004B0DF1   8B4DF8                 mov     ecx, [ebp-$08]
004B0DF4   8B89F4020000           mov     ecx, [ecx+$02F4]
004B0DFA   2B5144                 sub     edx, dword ptr [ecx+$44]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
004B0DFD   E86EB3F9FF             call    0044C170
004B0E02   8B45F8                 mov     eax, [ebp-$08]

* Reference to field TLoginDialog.Height : Integer
|
004B0E05   8B504C                 mov     edx, [eax+$4C]
004B0E08   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Bevel : TBevel
|
004B0E0B   8B80F4020000           mov     eax, [eax+$02F4]
004B0E11   2B5044                 sub     edx, dword ptr [eax+$44]
004B0E14   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Controls.TControl.SetHeight(TControl;Integer);
|
004B0E17   E8A0B3F9FF             call    0044C1BC
004B0E1C   8B13                   mov     edx, [ebx]
004B0E1E   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
004B0E21   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
004B0E27   E808BCF9FF             call    0044CA34
004B0E2C   C645FF00               mov     byte ptr [ebp-$01], $00
004B0E30   833B00                 cmp     dword ptr [ebx], +$00
004B0E33   7511                   jnz     004B0E46
004B0E35   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
004B0E38   8B9018030000           mov     edx, [eax+$0318]
004B0E3E   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Forms.TCustomForm.SetActiveControl(TCustomForm;TWinControl);
|
004B0E41   E8AA6FFBFF             call    00467DF0
004B0E46   8B45F8                 mov     eax, [ebp-$08]
004B0E49   8B10                   mov     edx, [eax]

* Reference to method TLoginDialog.ShowModal()
|
004B0E4B   FF92E8000000           call    dword ptr [edx+$00E8]
004B0E51   48                     dec     eax
004B0E52   753A                   jnz     004B0E8E
004B0E54   8D55F0                 lea     edx, [ebp-$10]
004B0E57   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
004B0E5A   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004B0E60   E89FBBF9FF             call    0044CA04
004B0E65   8B55F0                 mov     edx, [ebp-$10]
004B0E68   8BC3                   mov     eax, ebx

* Reference to: System.@LStrAsg(void;void;void;void);
|
004B0E6A   E84D3DF5FF             call    00404BBC
004B0E6F   8D55EC                 lea     edx, [ebp-$14]
004B0E72   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Password : TEdit
|
004B0E75   8B8014030000           mov     eax, [eax+$0314]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004B0E7B   E884BBF9FF             call    0044CA04
004B0E80   8B55EC                 mov     edx, [ebp-$14]
004B0E83   8BC6                   mov     eax, esi

* Reference to: System.@LStrAsg(void;void;void;void);
|
004B0E85   E8323DF5FF             call    00404BBC
004B0E8A   C645FF01               mov     byte ptr [ebp-$01], $01
004B0E8E   33C0                   xor     eax, eax
004B0E90   5A                     pop     edx
004B0E91   59                     pop     ecx
004B0E92   59                     pop     ecx
004B0E93   648910                 mov     fs:[eax], edx

****** FINALLY
|
004B0E96   68AB0E4B00             push    $004B0EAB
004B0E9B   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.TObject.Free(TObject);
|
004B0E9E   E8952EF5FF             call    00403D38
004B0EA3   C3                     ret


* Reference to: System.@HandleFinally;
|
004B0EA4   E92336F5FF             jmp     004044CC
004B0EA9   EBF0                   jmp     004B0E9B

****** END
|
004B0EAB   33C0                   xor     eax, eax
004B0EAD   5A                     pop     edx
004B0EAE   59                     pop     ecx
004B0EAF   59                     pop     ecx
004B0EB0   648910                 mov     fs:[eax], edx

****** FINALLY
|
004B0EB3   68D50E4B00             push    $004B0ED5
004B0EB8   8D45EC                 lea     eax, [ebp-$14]
004B0EBB   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
004B0EC0   E8C73CF5FF             call    00404B8C
004B0EC5   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
004B0EC8   E89B3CF5FF             call    00404B68
004B0ECD   C3                     ret


* Reference to: System.@HandleFinally;
|
004B0ECE   E9F935F5FF             jmp     004044CC
004B0ED3   EBE3                   jmp     004B0EB8

****** END
|
004B0ED5   8A45FF                 mov     al, byte ptr [ebp-$01]
004B0ED8   5E                     pop     esi
004B0ED9   5B                     pop     ebx
004B0EDA   8BE5                   mov     esp, ebp
004B0EDC   5D                     pop     ebp
004B0EDD   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
Framework/API calls: Forms.TScreen.SetCursor(TScreen;TCursor);; TScreen instance
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TLoginDialog._PROC_004B0F28(Sender : TObject);
begin
(*

* Reference to TScreen instance
|
004B0F28   8B15C8CC6100           mov     edx, [$0061CCC8]
004B0F2E   8B12                   mov     edx, [edx]
004B0F30   92                     xchg    eax, edx

* Reference to: Forms.TScreen.SetCursor(TScreen;TCursor);
|
004B0F31   E866A2FBFF             call    0046B19C
004B0F36   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
Strings/files/dialog text: ']Ã‹Àƒ-4Ýa'; 'éj5õÿëø]Ã‹Àƒ-4Ýa'
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TLoginDialog._PROC_004B0F38(Sender : TObject);
begin
(*
004B0F38   55                     push    ebp
004B0F39   8BEC                   mov     ebp, esp
004B0F3B   33C0                   xor     eax, eax
004B0F3D   55                     push    ebp

* Possible String Reference to: 'éj5õÿëø]Ã‹Àƒ-4Ýa'
|
004B0F3E   685D0F4B00             push    $004B0F5D

***** TRY
|
004B0F43   64FF30                 push    dword ptr fs:[eax]
004B0F46   648920                 mov     fs:[eax], esp
004B0F49   FF0534DD6100           inc     dword ptr [$0061DD34]
004B0F4F   33C0                   xor     eax, eax
004B0F51   5A                     pop     edx
004B0F52   59                     pop     ecx
004B0F53   59                     pop     ecx
004B0F54   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-4Ýa'
|
004B0F57   68640F4B00             push    $004B0F64
004B0F5C   C3                     ret


* Reference to: System.@HandleFinally;
|
004B0F5D   E96A35F5FF             jmp     004044CC
004B0F62   EBF8                   jmp     004B0F5C

****** END
|
004B0F64   5D                     pop     ebp
004B0F65   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
Global state: GlobalVar_0061DD10; GlobalVar_0061DD14; GlobalVar_0061DD18; GlobalVar_0061DD1C
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TLoginDialog._PROC_004B0F68(Sender : TObject);
begin
(*
004B0F68   832D34DD610001         sub     dword ptr [$0061DD34], +$01
004B0F6F   732C                   jnb     004B0F9D

* Reference to pointer to GlobalVar_0061DD10
|
004B0F71   A1F0C26100             mov     eax, dword ptr [$0061C2F0]
004B0F76   C700D80A4B00           mov     dword ptr [eax], $004B0AD8

* Reference to pointer to GlobalVar_0061DD14
|
004B0F7C   A168C56100             mov     eax, dword ptr [$0061C568]
004B0F81   C700F00B4B00           mov     dword ptr [eax], $004B0BF0

* Reference to pointer to GlobalVar_0061DD18
|
004B0F87   A13CC36100             mov     eax, dword ptr [$0061C33C]
004B0F8C   C700200D4B00           mov     dword ptr [eax], $004B0D20

* Reference to pointer to GlobalVar_0061DD1C
|
004B0F92   A1ECC46100             mov     eax, dword ptr [$0061C4EC]
004B0F97   C700280F4B00           mov     dword ptr [eax], $004B0F28
004B0F9D   C3                     ret

*)
end;

end.
