unit DBPWDlg;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls;

type
  TPasswordDialog=class(TForm)
    GroupBox1: TGroupBox;
    Edit: TEdit;
    AddButton: TButton;
    RemoveButton: TButton;
    RemoveAllButton: TButton;
    OKButton: TButton;
    CancelButton: TButton;
    procedure EditChange(Sender : TObject);
    procedure AddButtonClick(Sender : TObject);
    procedure RemoveButtonClick(Sender : TObject);
    procedure RemoveAllButtonClick(Sender : TObject);
    procedure OKButtonClick(Sender : TObject);
    procedure _PROC_004B147C(Sender : TObject);
    procedure _PROC_004B14B8(Sender : TObject);
  private
    OFFS_030C: Byte;
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  PasswordDialog: TPasswordDialog;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TPasswordDialog.EditChange(Sender : TObject);
begin
(*
004B1298   55                     push    ebp
004B1299   8BEC                   mov     ebp, esp
004B129B   6A00                   push    $00
004B129D   53                     push    ebx
004B129E   56                     push    esi
004B129F   8BF0                   mov     esi, eax
004B12A1   33C0                   xor     eax, eax
004B12A3   55                     push    ebp

* Possible String Reference to: '�1����^[Y]Ë�U��j'
|
004B12A4   6812134B00             push    $004B1312

***** TRY
|
004B12A9   64FF30                 push    dword ptr fs:[eax]
004B12AC   648920                 mov     fs:[eax], esp
004B12AF   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TPasswordDialog.Edit : TEdit
|
004B12B2   8B86F4020000           mov     eax, [esi+$02F4]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004B12B8   E847B7F9FF             call    0044CA04
004B12BD   837DFC00               cmp     dword ptr [ebp-$04], +$00
004B12C1   0F95C3                 setnz   bl
004B12C4   8BD3                   mov     edx, ebx

* Reference to control TPasswordDialog.AddButton : TButton
|
004B12C6   8B86F8020000           mov     eax, [esi+$02F8]
004B12CC   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
004B12CE   FF5164                 call    dword ptr [ecx+$64]
004B12D1   8BD3                   mov     edx, ebx

* Reference to control TPasswordDialog.RemoveButton : TButton
|
004B12D3   8B86FC020000           mov     eax, [esi+$02FC]
004B12D9   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
004B12DB   FF5164                 call    dword ptr [ecx+$64]
004B12DE   84DB                   test    bl, bl
004B12E0   750D                   jnz     004B12EF

* Reference to field TPasswordDialog.OFFS_030C : Byte
|
004B12E2   80BE0C03000000         cmp     byte ptr [esi+$030C], $00
004B12E9   7504                   jnz     004B12EF
004B12EB   33D2                   xor     edx, edx
004B12ED   EB02                   jmp     004B12F1
004B12EF   B201                   mov     dl, $01

* Reference to control TPasswordDialog.OKButton : TButton
|
004B12F1   8B8604030000           mov     eax, [esi+$0304]
004B12F7   8B08                   mov     ecx, [eax]

* Reference to method TButton.SetEnabled(Boolean)
|
004B12F9   FF5164                 call    dword ptr [ecx+$64]
004B12FC   33C0                   xor     eax, eax
004B12FE   5A                     pop     edx
004B12FF   59                     pop     ecx
004B1300   59                     pop     ecx
004B1301   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]Ë�U��j'
|
004B1304   6819134B00             push    $004B1319
004B1309   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
004B130C   E85738F5FF             call    00404B68
004B1311   C3                     ret


* Reference to: System.@HandleFinally;
|
004B1312   E9B531F5FF             jmp     004044CC
004B1317   EBF0                   jmp     004B1309

****** END
|
004B1319   5E                     pop     esi
004B131A   5B                     pop     ebx
004B131B   59                     pop     ecx
004B131C   5D                     pop     ebp
004B131D   C3                     ret

*)
end;

procedure TPasswordDialog.AddButtonClick(Sender : TObject);
begin
(*
004B1320   55                     push    ebp
004B1321   8BEC                   mov     ebp, esp
004B1323   6A00                   push    $00
004B1325   53                     push    ebx
004B1326   8BD8                   mov     ebx, eax
004B1328   33C0                   xor     eax, eax
004B132A   55                     push    ebp

* Possible String Reference to: '�<1����[Y]Ë�U��j'
|
004B132B   688B134B00             push    $004B138B

***** TRY
|
004B1330   64FF30                 push    dword ptr fs:[eax]
004B1333   648920                 mov     fs:[eax], esp
004B1336   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TPasswordDialog.Edit : TEdit
|
004B1339   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004B133F   E8C0B6F9FF             call    0044CA04
004B1344   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TPasswordDialog.OFFS_0310
|
004B1347   8B8310030000           mov     eax, [ebx+$0310]
004B134D   8B08                   mov     ecx, [eax]
004B134F   FF510C                 call    dword ptr [ecx+$0C]

* Reference to field TPasswordDialog.OFFS_030C : Byte
|
004B1352   C6830C03000001         mov     byte ptr [ebx+$030C], $01

* Reference to control TPasswordDialog.Edit : TEdit
|
004B1359   8B83F4020000           mov     eax, [ebx+$02F4]
004B135F   8B10                   mov     edx, [eax]

* Reference to method TEdit.Clear()
|
004B1361   FF92DC000000           call    dword ptr [edx+$00DC]

* Reference to control TPasswordDialog.Edit : TEdit
|
004B1367   8B83F4020000           mov     eax, [ebx+$02F4]
004B136D   8B10                   mov     edx, [eax]

* Reference to method TEdit.SetFocus()
|
004B136F   FF92C0000000           call    dword ptr [edx+$00C0]
004B1375   33C0                   xor     eax, eax
004B1377   5A                     pop     edx
004B1378   59                     pop     ecx
004B1379   59                     pop     ecx
004B137A   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]Ë�U��j'
|
004B137D   6892134B00             push    $004B1392
004B1382   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
004B1385   E8DE37F5FF             call    00404B68
004B138A   C3                     ret


* Reference to: System.@HandleFinally;
|
004B138B   E93C31F5FF             jmp     004044CC
004B1390   EBF0                   jmp     004B1382

****** END
|
004B1392   5B                     pop     ebx
004B1393   59                     pop     ecx
004B1394   5D                     pop     ebp
004B1395   C3                     ret

*)
end;

procedure TPasswordDialog.RemoveButtonClick(Sender : TObject);
begin
(*
004B1398   55                     push    ebp
004B1399   8BEC                   mov     ebp, esp
004B139B   6A00                   push    $00
004B139D   53                     push    ebx
004B139E   8BD8                   mov     ebx, eax
004B13A0   33C0                   xor     eax, eax
004B13A2   55                     push    ebp
004B13A3   68FC134B00             push    $004B13FC

***** TRY
|
004B13A8   64FF30                 push    dword ptr fs:[eax]
004B13AB   648920                 mov     fs:[eax], esp
004B13AE   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TPasswordDialog.Edit : TEdit
|
004B13B1   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004B13B7   E848B6F9FF             call    0044CA04
004B13BC   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TPasswordDialog.OFFS_0310
|
004B13BF   8B8310030000           mov     eax, [ebx+$0310]
004B13C5   8B08                   mov     ecx, [eax]
004B13C7   FF5110                 call    dword ptr [ecx+$10]

* Reference to control TPasswordDialog.Edit : TEdit
|
004B13CA   8B83F4020000           mov     eax, [ebx+$02F4]
004B13D0   8B10                   mov     edx, [eax]

* Reference to method TEdit.Clear()
|
004B13D2   FF92DC000000           call    dword ptr [edx+$00DC]

* Reference to control TPasswordDialog.Edit : TEdit
|
004B13D8   8B83F4020000           mov     eax, [ebx+$02F4]
004B13DE   8B10                   mov     edx, [eax]

* Reference to method TEdit.SetFocus()
|
004B13E0   FF92C0000000           call    dword ptr [edx+$00C0]
004B13E6   33C0                   xor     eax, eax
004B13E8   5A                     pop     edx
004B13E9   59                     pop     ecx
004B13EA   59                     pop     ecx
004B13EB   648910                 mov     fs:[eax], edx

****** FINALLY
|
004B13EE   6803144B00             push    $004B1403
004B13F3   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
004B13F6   E86D37F5FF             call    00404B68
004B13FB   C3                     ret


* Reference to: System.@HandleFinally;
|
004B13FC   E9CB30F5FF             jmp     004044CC
004B1401   EBF0                   jmp     004B13F3

****** END
|
004B1403   5B                     pop     ebx
004B1404   59                     pop     ecx
004B1405   5D                     pop     ebp
004B1406   C3                     ret

*)
end;

procedure TPasswordDialog.RemoveAllButtonClick(Sender : TObject);
begin
(*
004B1408   53                     push    ebx
004B1409   8BD8                   mov     ebx, eax

* Reference to field TPasswordDialog.OFFS_0310
|
004B140B   8B8310030000           mov     eax, [ebx+$0310]
004B1411   8B10                   mov     edx, [eax]
004B1413   FF5214                 call    dword ptr [edx+$14]

* Reference to control TPasswordDialog.Edit : TEdit
|
004B1416   8B83F4020000           mov     eax, [ebx+$02F4]
004B141C   8B10                   mov     edx, [eax]

* Reference to method TEdit.SetFocus()
|
004B141E   FF92C0000000           call    dword ptr [edx+$00C0]
004B1424   5B                     pop     ebx
004B1425   C3                     ret

*)
end;

procedure TPasswordDialog.OKButtonClick(Sender : TObject);
begin
(*
004B1428   55                     push    ebp
004B1429   8BEC                   mov     ebp, esp
004B142B   6A00                   push    $00
004B142D   53                     push    ebx
004B142E   8BD8                   mov     ebx, eax
004B1430   33C0                   xor     eax, eax
004B1432   55                     push    ebp
004B1433   6870144B00             push    $004B1470

***** TRY
|
004B1438   64FF30                 push    dword ptr fs:[eax]
004B143B   648920                 mov     fs:[eax], esp
004B143E   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TPasswordDialog.Edit : TEdit
|
004B1441   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
004B1447   E8B8B5F9FF             call    0044CA04
004B144C   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TPasswordDialog.OFFS_0310
|
004B144F   8B8310030000           mov     eax, [ebx+$0310]
004B1455   8B08                   mov     ecx, [eax]
004B1457   FF510C                 call    dword ptr [ecx+$0C]
004B145A   33C0                   xor     eax, eax
004B145C   5A                     pop     edx
004B145D   59                     pop     ecx
004B145E   59                     pop     ecx
004B145F   648910                 mov     fs:[eax], edx

****** FINALLY
|
004B1462   6877144B00             push    $004B1477
004B1467   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
004B146A   E8F936F5FF             call    00404B68
004B146F   C3                     ret


* Reference to: System.@HandleFinally;
|
004B1470   E95730F5FF             jmp     004044CC
004B1475   EBF0                   jmp     004B1467

****** END
|
004B1477   5B                     pop     ebx
004B1478   59                     pop     ecx
004B1479   5D                     pop     ebp
004B147A   C3                     ret

*)
end;

procedure TPasswordDialog._PROC_004B147C(Sender : TObject);
begin
(*
004B147C   55                     push    ebp
004B147D   8BEC                   mov     ebp, esp
004B147F   33C0                   xor     eax, eax
004B1481   55                     push    ebp
004B1482   68AC144B00             push    $004B14AC

***** TRY
|
004B1487   64FF30                 push    dword ptr fs:[eax]
004B148A   648920                 mov     fs:[eax], esp
004B148D   FF0538DD6100           inc     dword ptr [$0061DD38]
004B1493   7509                   jnz     004B149E

* Reference to pointer to GlobalVar_0061DD20
|
004B1495   A13CC26100             mov     eax, dword ptr [$0061C23C]
004B149A   33D2                   xor     edx, edx
004B149C   8910                   mov     [eax], edx
004B149E   33C0                   xor     eax, eax
004B14A0   5A                     pop     edx
004B14A1   59                     pop     ecx
004B14A2   59                     pop     ecx
004B14A3   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Í@'
|
004B14A6   68B3144B00             push    $004B14B3
004B14AB   C3                     ret


* Reference to: System.@HandleFinally;
|
004B14AC   E91B30F5FF             jmp     004044CC
004B14B1   EBF8                   jmp     004B14AB

****** END
|
004B14B3   5D                     pop     ebp
004B14B4   C3                     ret

*)
end;

procedure TPasswordDialog._PROC_004B14B8(Sender : TObject);
begin
(*
004B14B8   832D38DD610001         sub     dword ptr [$0061DD38], +$01
004B14BF   730B                   jnb     004B14CC

* Reference to pointer to GlobalVar_0061DD20
|
004B14C1   A13CC26100             mov     eax, dword ptr [$0061C23C]
004B14C6   C70024124B00           mov     dword ptr [eax], $004B1224
004B14CC   C3                     ret

*)
end;

end.
