unit QRLablEd;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls,
  {$IFDEF FPC}MaskEdit{$ELSE}Mask{$ENDIF};
type
  TQRLabelEditorForm=class(TForm)
    GroupBox1: TGroupBox;
    Label1: TLabel;
    Value: TEdit;
{$IFDEF FPC}
    chkAutoSize: TCheckBox;
{$ELSE}
    AutoSize: TCheckBox;
{$ENDIF}
    Stretch: TCheckBox;
    FontDialog1: TFontDialog;
    OKBtn: TButton;
    Button4: TButton;
    Transparent: TCheckBox;
{$IFDEF FPC}
    edtWidth: TMaskEdit;
    edtHeight: TMaskEdit;
{$ELSE}
    Width: TMaskEdit;
    Height: TMaskEdit;
{$ENDIF}
    Label2: TLabel;
    Label3: TLabel;
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  QRLabelEditorForm: TQRLabelEditorForm;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$IFDEF FPC}
{$R *.lfm}
{$ELSE}
{$R *.dfm}
{$ENDIF}

end.