unit QRPrgres;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ComCtrls;
type
  TQRProgressForm=class(TForm)
    Info: TLabel;
    CancelButton: TButton;
    Gauge: TProgressBar;
    procedure CancelButtonClick(Sender : TObject);
    procedure _PROC_005035D5(Sender : TObject);
    procedure _PROC_00503604(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  QRProgressForm: TQRProgressForm;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TQRProgressForm.CancelButtonClick(Sender : TObject);
begin
(*

* Reference to field TQRProgressForm.OFFS_02FC
|
005035C8   8B80FC020000           mov     eax, [eax+$02FC]

* Reference to: QRPrntr.Proc_00520BD0
|
005035CE   E8FDD50100             call    00520BD0
005035D3   C3                     ret

*)
end;

procedure TQRProgressForm._PROC_005035D5(Sender : TObject);
begin
(*
005035D5   8BEC                   mov     ebp, esp
005035D7   33C0                   xor     eax, eax
005035D9   55                     push    ebp
005035DA   68F9355000             push    $005035F9

***** TRY
|
005035DF   64FF30                 push    dword ptr fs:[eax]
005035E2   648920                 mov     fs:[eax], esp
005035E5   FF0528DE6100           inc     dword ptr [$0061DE28]
005035EB   33C0                   xor     eax, eax
005035ED   5A                     pop     edx
005035EE   59                     pop     ecx
005035EF   59                     pop     ecx
005035F0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ë��-(�a'
|
005035F3   6800365000             push    $00503600
005035F8   C3                     ret


* Reference to: System.@HandleFinally;
|
005035F9   E9CE0EF0FF             jmp     004044CC
005035FE   EBF8                   jmp     005035F8

****** END
|
00503600   5D                     pop     ebp
00503601   C3                     ret

*)
end;

procedure TQRProgressForm._PROC_00503604(Sender : TObject);
begin
(*
00503604   832D28DE610001         sub     dword ptr [$0061DE28], +$01
0050360B   C3                     ret

*)
end;

end.