unit QRPrev;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ComCtrls, Buttons, QRPrntr;
type
  TQRStandardPreview=class(TForm)
    StatusBar: TStatusBar;
    ToolBar1: TToolBar;
    ZoomFit: TToolButton;
    Zoom100: TToolButton;
    ZoomToWidth: TToolButton;
    Separator1: TToolButton;
    FirstPage: TToolButton;
    PreviousPage: TToolButton;
    ToolButton2: TToolButton;
    LastPage: TToolButton;
    Separator2: TToolButton;
    PrintSetup: TToolButton;
    Print: TToolButton;
    Separator3: TToolButton;
    SaveReport: TToolButton;
    LoadReport: TToolButton;
    Separator4: TToolButton;
    Images: TImageList;
    ToolButton1: TToolButton;
    ExitButton: TSpeedButton;
    QRPreview: TQRPreview;
    procedure FormClose(Sender : TObject);
    procedure ZoomToFitClick(Sender : TObject);
    procedure ZoomTo100Click(Sender : TObject);
    procedure ZoomToWidthClick(Sender : TObject);
    procedure FirstPageClick(Sender : TObject);
    procedure PrevPageClick(Sender : TObject);
    procedure NextPageClick(Sender : TObject);
    procedure LastPageClick(Sender : TObject);
    procedure PrintClick(Sender : TObject);
    procedure ExitClick(Sender : TObject);
    procedure FormResize(Sender : TObject);
    procedure FormKeyDown(Sender : TObject);
    procedure SaveClick(Sender : TObject);
    procedure PrintSetupClick(Sender : TObject);
    procedure LoadClick(Sender : TObject);
    procedure QRPreviewPageAvailable(Sender : TObject);
    procedure QRPreviewProgressUpdate(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure _PROC_0051CC40(Sender : TObject);
    procedure _PROC_0051CE14(Sender : TObject);
    procedure _PROC_0051CE47(Sender : TObject);
    procedure _PROC_0051CED0(Sender : TObject);
    procedure _PROC_0051D30D(Sender : TObject);
    procedure _PROC_0051D33C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  QRStandardPreview: TQRStandardPreview;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

{ ASM listing resource map; extracted from commented binary evidence only.
Unresolved field offsets: OFFS_0344
Framework/API calls: QRPrntr.TQRPrinter.ClosePreview(TQRPrinter;TWinControl);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.FormClose(Sender : TObject);
begin
(*
0051CC28   53                     push    ebx
0051CC29   8BD9                   mov     ebx, ecx
0051CC2B   8BD0                   mov     edx, eax

* Reference to field TQRStandardPreview.OFFS_0344
|
0051CC2D   8B8044030000           mov     eax, [eax+$0344]

* Reference to: QRPrntr.TQRPrinter.ClosePreview(TQRPrinter;TWinControl);
|
0051CC33   E8043A0000             call    0052063C
0051CC38   C60302                 mov     byte ptr [ebx], $02
0051CC3B   5B                     pop     ebx
0051CC3C   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.QRPreview (TQRPreview); TApplication instance
Framework/API calls: Forms.TApplication.ProcessMessages(TApplication);;
    QRPrntr.TQRPreview.ZoomToFit(TQRPreview);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.ZoomToFitClick(Sender : TObject);
begin
(*
0051CD1C   53                     push    ebx
0051CD1D   8BD8                   mov     ebx, eax

* Reference to TApplication instance
|
0051CD1F   A10CC96100             mov     eax, dword ptr [$0061C90C]
0051CD24   8B00                   mov     eax, [eax]

* Reference to: Forms.TApplication.ProcessMessages(TApplication);
|
0051CD26   E86902F5FF             call    0046CF94

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CD2B   8B8340030000           mov     eax, [ebx+$0340]

* Reference to: QRPrntr.TQRPreview.ZoomToFit(TQRPreview);
|
0051CD31   E80A290000             call    0051F640
0051CD36   5B                     pop     ebx
0051CD37   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.QRPreview (TQRPreview); TApplication instance
Framework/API calls: Forms.TApplication.ProcessMessages(TApplication);;
    QRPrntr.TQRPreview.SetZoom(TQRPreview;Integer);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.ZoomTo100Click(Sender : TObject);
begin
(*
0051CD38   53                     push    ebx
0051CD39   8BD8                   mov     ebx, eax

* Reference to TApplication instance
|
0051CD3B   A10CC96100             mov     eax, dword ptr [$0061C90C]
0051CD40   8B00                   mov     eax, [eax]

* Reference to: Forms.TApplication.ProcessMessages(TApplication);
|
0051CD42   E84D02F5FF             call    0046CF94
0051CD47   BA64000000             mov     edx, $00000064

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CD4C   8B8340030000           mov     eax, [ebx+$0340]

* Reference to: QRPrntr.TQRPreview.SetZoom(TQRPreview;Integer);
|
0051CD52   E8C9280000             call    0051F620
0051CD57   5B                     pop     ebx
0051CD58   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.QRPreview (TQRPreview); TApplication instance
Framework/API calls: Forms.TApplication.ProcessMessages(TApplication);;
    QRPrntr.TQRPreview.ZoomToWidth(TQRPreview);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.ZoomToWidthClick(Sender : TObject);
begin
(*
0051CD5C   53                     push    ebx
0051CD5D   8BD8                   mov     ebx, eax

* Reference to TApplication instance
|
0051CD5F   A10CC96100             mov     eax, dword ptr [$0061C90C]
0051CD64   8B00                   mov     eax, [eax]

* Reference to: Forms.TApplication.ProcessMessages(TApplication);
|
0051CD66   E82902F5FF             call    0046CF94

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CD6B   8B8340030000           mov     eax, [ebx+$0340]

* Reference to: QRPrntr.TQRPreview.ZoomToWidth(TQRPreview);
|
0051CD71   E89E290000             call    0051F714
0051CD76   5B                     pop     ebx
0051CD77   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.QRPreview (TQRPreview)
Framework/API calls: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);;
    QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.FirstPageClick(Sender : TObject);
begin
(*
0051CD78   53                     push    ebx
0051CD79   8BD8                   mov     ebx, eax
0051CD7B   BA01000000             mov     edx, $00000001

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CD80   8B8340030000           mov     eax, [ebx+$0340]

* Reference to: QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);
|
0051CD86   E835260000             call    0051F3C0
0051CD8B   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);
|
0051CD8D   E8AEFEFFFF             call    0051CC40
0051CD92   5B                     pop     ebx
0051CD93   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.QRPreview (TQRPreview)
Unresolved field offsets: OFFS_023C
Framework/API calls: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);;
    QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.PrevPageClick(Sender : TObject);
begin
(*
0051CD94   53                     push    ebx
0051CD95   8BD8                   mov     ebx, eax

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CD97   8B8340030000           mov     eax, [ebx+$0340]

* Reference to field TQRPreview.OFFS_023C
|
0051CD9D   8B903C020000           mov     edx, [eax+$023C]
0051CDA3   4A                     dec     edx

* Reference to: QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);
|
0051CDA4   E817260000             call    0051F3C0
0051CDA9   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);
|
0051CDAB   E890FEFFFF             call    0051CC40
0051CDB0   5B                     pop     ebx
0051CDB1   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.QRPreview (TQRPreview)
Unresolved field offsets: OFFS_023C
Framework/API calls: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);;
    QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.NextPageClick(Sender : TObject);
begin
(*
0051CDB4   53                     push    ebx
0051CDB5   8BD8                   mov     ebx, eax

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CDB7   8B8340030000           mov     eax, [ebx+$0340]

* Reference to field TQRPreview.OFFS_023C
|
0051CDBD   8B903C020000           mov     edx, [eax+$023C]
0051CDC3   42                     inc     edx

* Reference to: QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);
|
0051CDC4   E8F7250000             call    0051F3C0
0051CDC9   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);
|
0051CDCB   E870FEFFFF             call    0051CC40
0051CDD0   5B                     pop     ebx
0051CDD1   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.QRPreview (TQRPreview)
Unresolved field offsets: OFFS_0344
Framework/API calls: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);;
    QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.LastPageClick(Sender : TObject);
begin
(*
0051CDD4   53                     push    ebx
0051CDD5   8BD8                   mov     ebx, eax

* Reference to field TQRStandardPreview.OFFS_0344
|
0051CDD7   8B8344030000           mov     eax, [ebx+$0344]
0051CDDD   8B506C                 mov     edx, [eax+$6C]

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CDE0   8B8340030000           mov     eax, [ebx+$0340]

* Reference to: QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);
|
0051CDE6   E8D5250000             call    0051F3C0
0051CDEB   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);
|
0051CDED   E84EFEFFFF             call    0051CC40
0051CDF2   5B                     pop     ebx
0051CDF3   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
Unresolved field offsets: OFFS_0344
Framework/API calls: QRPrntr.TQRPrinter.Print(TQRPrinter);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.PrintClick(Sender : TObject);
begin
(*

* Reference to field TQRStandardPreview.OFFS_0344
|
0051CDF4   8B8044030000           mov     eax, [eax+$0344]

* Reference to: QRPrntr.TQRPrinter.Print(TQRPrinter);
|
0051CDFA   E89D440000             call    0052129C
0051CDFF   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
Framework/API calls: Forms.TCustomForm.Close(TCustomForm);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.ExitClick(Sender : TObject);
begin
(*

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
0051CE00   E84BC9F4FF             call    00469750
0051CE05   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.QRPreview (TQRPreview)
Framework/API calls: QRPrntr.TQRPreview.UpdateZoom(TQRPreview);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.FormResize(Sender : TObject);
begin
(*

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CE08   8B8040030000           mov     eax, [eax+$0340]

* Reference to: QRPrntr.TQRPreview.UpdateZoom(TQRPreview);
|
0051CE0E   E859260000             call    0051F46C
0051CE13   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
  Unknown: no symbolic resource labels found; resources are represented only by raw offsets or indirect calls.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.FormKeyDown(Sender : TObject);
begin
(*
0051CE28   55                     push    ebp
0051CE29   8BEC                   mov     ebp, esp
0051CE2B   53                     push    ebx
0051CE2C   8BD8                   mov     ebx, eax
0051CE2E   0FB701                 movzx   eax, word ptr [ecx]
0051CE31   83C0E5                 add     eax, -$1B
0051CE34   83F809                 cmp     eax, +$09
0051CE37   0F878E000000           jnbe    0051CECB
0051CE3D   FF248544CE5100         jmp     dword ptr [$51CE44+eax*4]
0051CE44   C2CE51                 ret     $51CE

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TApplication instance
Global state: GlobalVar_0061DEC0
Unresolved field offsets: OFFS_0004; OFFS_0344
Framework/API calls: class TSaveDialog; Classes.TList.Get(TList;Integer):Pointer;;
    Dialogs.TOpenDialog.Create(TOpenDialog;boolean;TComponent);;
    Dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;;
    Dialogs.TOpenDialog.GetFilterIndex(TOpenDialog):Integer;; method TSaveDialog.Execute();
    QRPrntr.TQRExportFilterLibrary.GetSaveDialogFilter(TQRExportFilterLibrary):AnsiString;;
    QRPrntr.TQRPrinter.ExportToFilter(TQRPrinter;TQRExportFilter);;
    QRPrntr.TQRPrinter.Save(TQRPrinter;AnsiString);;
    QRPrntr.TQRStream.CreateFromFile(TQRStream;boolean;AnsiString);;
    System.LoadResString(PResStringRec):String;; System.TObject.Free(TObject);
Strings/files/dialog text: '[��]�'; 'QRP'; '�t����[��]�'
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.SaveClick(Sender : TObject);
begin
(*
0051CED4   55                     push    ebp
0051CED5   8BEC                   mov     ebp, esp
0051CED7   33C9                   xor     ecx, ecx
0051CED9   51                     push    ecx
0051CEDA   51                     push    ecx
0051CEDB   51                     push    ecx
0051CEDC   51                     push    ecx
0051CEDD   51                     push    ecx
0051CEDE   53                     push    ebx
0051CEDF   8BD8                   mov     ebx, eax
0051CEE1   33C0                   xor     eax, eax
0051CEE3   55                     push    ebp

* Possible String Reference to: '�t����[��]�'
|
0051CEE4   683ED05100             push    $0051D03E

***** TRY
|
0051CEE9   64FF30                 push    dword ptr fs:[eax]
0051CEEC   648920                 mov     fs:[eax], esp
0051CEEF   33C0                   xor     eax, eax
0051CEF1   8945FC                 mov     [ebp-$04], eax

* Reference to TApplication instance
|
0051CEF4   8B0D0CC96100           mov     ecx, [$0061C90C]
0051CEFA   8B09                   mov     ecx, [ecx]
0051CEFC   B201                   mov     dl, $01

* Reference to class TSaveDialog
|
0051CEFE   A148284400             mov     eax, dword ptr [$00442848]

* Reference to: Dialogs.TOpenDialog.Create(TOpenDialog;boolean;TComponent);
|
0051CF03   E8E066F2FF             call    004435E8
0051CF08   8945F8                 mov     [ebp-$08], eax
0051CF0B   33C0                   xor     eax, eax
0051CF0D   55                     push    ebp
0051CF0E   6814D05100             push    $0051D014

***** TRY
|
0051CF13   64FF30                 push    dword ptr fs:[eax]
0051CF16   648920                 mov     fs:[eax], esp
0051CF19   8B45F8                 mov     eax, [ebp-$08]

* Reference to field TSaveDialog.Title : string
|
0051CF1C   8D5070                 lea     edx, [eax+$70]
0051CF1F   A108C36100             mov     eax, dword ptr [$0061C308]

* Reference to: System.LoadResString(PResStringRec):String;
|
0051CF24   E8A7A0EEFF             call    00406FD0
0051CF29   8D55F4                 lea     edx, [ebp-$0C]

* Reference to pointer to GlobalVar_0061DEC0
|
0051CF2C   A198C76100             mov     eax, dword ptr [$0061C798]
0051CF31   8B00                   mov     eax, [eax]

* Reference to: QRPrntr.TQRExportFilterLibrary.GetSaveDialogFilter(TQRExportFilterLibrary):AnsiString;
|
0051CF33   E880290000             call    0051F8B8
0051CF38   8B55F4                 mov     edx, [ebp-$0C]
0051CF3B   8B45F8                 mov     eax, [ebp-$08]
0051CF3E   83C060                 add     eax, +$60

* Reference to: System.@LStrAsg(void;void;void;void);
|
0051CF41   E8767CEEFF             call    00404BBC
0051CF46   8B45F8                 mov     eax, [ebp-$08]
0051CF49   83C074                 add     eax, +$74

* Possible String Reference to: 'QRP'
|
0051CF4C   BA54D05100             mov     edx, $0051D054

* Reference to: System.@LStrAsg(void;void;void;void);
|
0051CF51   E8667CEEFF             call    00404BBC
0051CF56   8B45F8                 mov     eax, [ebp-$08]
0051CF59   8B10                   mov     edx, [eax]

* Reference to method TSaveDialog.Execute()
|
0051CF5B   FF523C                 call    dword ptr [edx+$3C]
0051CF5E   84C0                   test    al, al
0051CF60   0F8498000000           jz      0051CFFE
0051CF66   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Dialogs.TOpenDialog.GetFilterIndex(TOpenDialog):Integer;
|
0051CF69   E81A6FF2FF             call    00443E88
0051CF6E   48                     dec     eax
0051CF6F   751B                   jnz     0051CF8C
0051CF71   8D55F0                 lea     edx, [ebp-$10]
0051CF74   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;
|
0051CF77   E8B46EF2FF             call    00443E30
0051CF7C   8B55F0                 mov     edx, [ebp-$10]

* Reference to field TQRStandardPreview.OFFS_0344
|
0051CF7F   8B8344030000           mov     eax, [ebx+$0344]

* Reference to: QRPrntr.TQRPrinter.Save(TQRPrinter;AnsiString);
|
0051CF85   E81E420000             call    005211A8
0051CF8A   EB72                   jmp     0051CFFE
0051CF8C   33C0                   xor     eax, eax
0051CF8E   55                     push    ebp
0051CF8F   68F7CF5100             push    $0051CFF7

***** TRY
|
0051CF94   64FF30                 push    dword ptr fs:[eax]
0051CF97   648920                 mov     fs:[eax], esp
0051CF9A   8D55EC                 lea     edx, [ebp-$14]
0051CF9D   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;
|
0051CFA0   E88B6EF2FF             call    00443E30
0051CFA5   8B45EC                 mov     eax, [ebp-$14]
0051CFA8   50                     push    eax
0051CFA9   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Dialogs.TOpenDialog.GetFilterIndex(TOpenDialog):Integer;
|
0051CFAC   E8D76EF2FF             call    00443E88
0051CFB1   8BD0                   mov     edx, eax
0051CFB3   83EA02                 sub     edx, +$02

* Reference to pointer to GlobalVar_0061DEC0
|
0051CFB6   A198C76100             mov     eax, dword ptr [$0061C798]
0051CFBB   8B00                   mov     eax, [eax]

* Reference to field GlobalVar_0061DEC0.OFFS_0004
|
0051CFBD   8B4004                 mov     eax, [eax+$04]

* Reference to: Classes.TList.Get(TList;Integer):Pointer;
|
0051CFC0   E84FCDEFFF             call    00419D14
0051CFC5   8B4004                 mov     eax, [eax+$04]
0051CFC8   B201                   mov     dl, $01
0051CFCA   59                     pop     ecx

* Reference to: QRPrntr.TQRStream.CreateFromFile(TQRStream;boolean;AnsiString);
|
0051CFCB   E8C8270000             call    0051F798
0051CFD0   8945FC                 mov     [ebp-$04], eax

* Reference to field TQRStandardPreview.OFFS_0344
|
0051CFD3   8B8344030000           mov     eax, [ebx+$0344]
0051CFD9   8B55FC                 mov     edx, [ebp-$04]

* Reference to: QRPrntr.TQRPrinter.ExportToFilter(TQRPrinter;TQRExportFilter);
|
0051CFDC   E81F420000             call    00521200
0051CFE1   33C0                   xor     eax, eax
0051CFE3   5A                     pop     edx
0051CFE4   59                     pop     ecx
0051CFE5   59                     pop     ecx
0051CFE6   648910                 mov     fs:[eax], edx

****** FINALLY
|
0051CFE9   68FECF5100             push    $0051CFFE
0051CFEE   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.TObject.Free(TObject);
|
0051CFF1   E8426DEEFF             call    00403D38
0051CFF6   C3                     ret


* Reference to: System.@HandleFinally;
|
0051CFF7   E9D074EEFF             jmp     004044CC
0051CFFC   EBF0                   jmp     0051CFEE

****** END
|
0051CFFE   33C0                   xor     eax, eax
0051D000   5A                     pop     edx
0051D001   59                     pop     ecx
0051D002   59                     pop     ecx
0051D003   648910                 mov     fs:[eax], edx

****** FINALLY
|
0051D006   681BD05100             push    $0051D01B
0051D00B   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.TObject.Free(TObject);
|
0051D00E   E8256DEEFF             call    00403D38
0051D013   C3                     ret


* Reference to: System.@HandleFinally;
|
0051D014   E9B374EEFF             jmp     004044CC
0051D019   EBF0                   jmp     0051D00B

****** END
|
0051D01B   33C0                   xor     eax, eax
0051D01D   5A                     pop     edx
0051D01E   59                     pop     ecx
0051D01F   59                     pop     ecx
0051D020   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[��]�'
|
0051D023   6845D05100             push    $0051D045
0051D028   8D45EC                 lea     eax, [ebp-$14]
0051D02B   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0051D030   E8577BEEFF             call    00404B8C
0051D035   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
0051D038   E82B7BEEFF             call    00404B68
0051D03D   C3                     ret


* Reference to: System.@HandleFinally;
|
0051D03E   E98974EEFF             jmp     004044CC
0051D043   EBE3                   jmp     0051D028

****** END
|
0051D045   5B                     pop     ebx
0051D046   8BE5                   mov     esp, ebp
0051D048   5D                     pop     ebp
0051D049   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
Unresolved field offsets: OFFS_0344
Framework/API calls: QRPrntr.TQRPrinter.PrintSetup(TQRPrinter);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.PrintSetupClick(Sender : TObject);
begin
(*

* Reference to field TQRStandardPreview.OFFS_0344
|
0051D058   8B8044030000           mov     eax, [eax+$0344]

* Reference to: QRPrntr.TQRPrinter.PrintSetup(TQRPrinter);
|
0051D05E   E859440000             call    005214BC
0051D063   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.Print (TToolButton); TQRStandardPreview.PrintSetup (TToolButton);
    TQRStandardPreview.QRPreview (TQRPreview); TApplication instance
Unresolved field offsets: OFFS_0238; OFFS_0344
Project calls: Unit_00408494.Proc_00409CD0
Framework/API calls: class TOpenDialog; Dialogs.ShowMessage(AnsiString);;
    Dialogs.TOpenDialog.Create(TOpenDialog;boolean;TComponent);;
    Dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;; method TOpenDialog.Execute(); method
    TToolButton.SetEnabled(Boolean); QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);;
    QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);;
    QRPrntr.TQRPreviewImage.SetPageNumber(TQRPreviewImage;Integer);;
    QRPrntr.TQRPrinter.Load(TQRPrinter;AnsiString);; System.LoadResString(PResStringRec):String;;
    System.Proc_00404EE0; System.TObject.Free(TObject);
Strings/files/dialog text: ' (' + '*.'; ')|*.'; '[��]�'; 'QRP'; '��r����[��]�'
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.LoadClick(Sender : TObject);
begin
(*
0051D064   55                     push    ebp
0051D065   8BEC                   mov     ebp, esp
0051D067   33C9                   xor     ecx, ecx
0051D069   51                     push    ecx
0051D06A   51                     push    ecx
0051D06B   51                     push    ecx
0051D06C   51                     push    ecx
0051D06D   51                     push    ecx
0051D06E   53                     push    ebx
0051D06F   8BD8                   mov     ebx, eax
0051D071   33C0                   xor     eax, eax
0051D073   55                     push    ebp

* Possible String Reference to: '��r����[��]�'
|
0051D074   68CED15100             push    $0051D1CE

***** TRY
|
0051D079   64FF30                 push    dword ptr fs:[eax]
0051D07C   648920                 mov     fs:[eax], esp

* Reference to TApplication instance
|
0051D07F   8B0D0CC96100           mov     ecx, [$0061C90C]
0051D085   8B09                   mov     ecx, [ecx]
0051D087   B201                   mov     dl, $01

* Reference to class TOpenDialog
|
0051D089   A150254400             mov     eax, dword ptr [$00442550]

* Reference to: Dialogs.TOpenDialog.Create(TOpenDialog;boolean;TComponent);
|
0051D08E   E85565F2FF             call    004435E8
0051D093   8945FC                 mov     [ebp-$04], eax
0051D096   33C0                   xor     eax, eax
0051D098   55                     push    ebp
0051D099   689CD15100             push    $0051D19C

***** TRY
|
0051D09E   64FF30                 push    dword ptr fs:[eax]
0051D0A1   648920                 mov     fs:[eax], esp
0051D0A4   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TOpenDialog.Title : string
|
0051D0A7   8D5070                 lea     edx, [eax+$70]
0051D0AA   A148CA6100             mov     eax, dword ptr [$0061CA48]

* Reference to: System.LoadResString(PResStringRec):String;
|
0051D0AF   E81C9FEEFF             call    00406FD0
0051D0B4   8D55F8                 lea     edx, [ebp-$08]
0051D0B7   A114C56100             mov     eax, dword ptr [$0061C514]

* Reference to: System.LoadResString(PResStringRec):String;
|
0051D0BC   E80F9FEEFF             call    00406FD0
0051D0C1   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: ' (' + '*.'
|
0051D0C4   68E4D15100             push    $0051D1E4

* Possible String Reference to: 'QRP'
|
0051D0C9   68F4D15100             push    $0051D1F4

* Possible String Reference to: ')|*.'
|
0051D0CE   6800D25100             push    $0051D200

* Possible String Reference to: 'QRP'
|
0051D0D3   68F4D15100             push    $0051D1F4
0051D0D8   8B45FC                 mov     eax, [ebp-$04]
0051D0DB   83C060                 add     eax, +$60
0051D0DE   BA05000000             mov     edx, $00000005

* Reference to: System.Proc_00404EE0
|
0051D0E3   E8F87DEEFF             call    00404EE0
0051D0E8   8B45FC                 mov     eax, [ebp-$04]
0051D0EB   8B10                   mov     edx, [eax]

* Reference to method TOpenDialog.Execute()
|
0051D0ED   FF523C                 call    dword ptr [edx+$3C]
0051D0F0   84C0                   test    al, al
0051D0F2   0F848E000000           jz      0051D186
0051D0F8   8D55F4                 lea     edx, [ebp-$0C]
0051D0FB   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;
|
0051D0FE   E82D6DF2FF             call    00443E30
0051D103   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: Unit_00408494.Proc_00409CD0
|
0051D106   E8C5CBEEFF             call    00409CD0
0051D10B   84C0                   test    al, al
0051D10D   7462                   jz      0051D171
0051D10F   8D55F0                 lea     edx, [ebp-$10]
0051D112   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;
|
0051D115   E8166DF2FF             call    00443E30
0051D11A   8B55F0                 mov     edx, [ebp-$10]

* Reference to field TQRStandardPreview.OFFS_0344
|
0051D11D   8B8344030000           mov     eax, [ebx+$0344]

* Reference to: QRPrntr.TQRPrinter.Load(TQRPrinter;AnsiString);
|
0051D123   E8FC3D0000             call    00520F24

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051D128   8B8340030000           mov     eax, [ebx+$0340]
0051D12E   BA01000000             mov     edx, $00000001

* Reference to: QRPrntr.TQRPreview.SetPageNumber(TQRPreview;Integer);
|
0051D133   E888220000             call    0051F3C0

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051D138   8B8340030000           mov     eax, [ebx+$0340]

* Reference to field TQRPreview.OFFS_0238
|
0051D13E   8B8038020000           mov     eax, [eax+$0238]
0051D144   BA01000000             mov     edx, $00000001

* Reference to: QRPrntr.TQRPreviewImage.SetPageNumber(TQRPreviewImage;Integer);
|
0051D149   E80E1F0000             call    0051F05C
0051D14E   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);
|
0051D150   E8EBFAFFFF             call    0051CC40

* Reference to control TQRStandardPreview.PrintSetup : TToolButton
|
0051D155   8B831C030000           mov     eax, [ebx+$031C]
0051D15B   33D2                   xor     edx, edx
0051D15D   8B08                   mov     ecx, [eax]

* Reference to method TToolButton.SetEnabled(Boolean)
|
0051D15F   FF5164                 call    dword ptr [ecx+$64]

* Reference to control TQRStandardPreview.Print : TToolButton
|
0051D162   8B8320030000           mov     eax, [ebx+$0320]
0051D168   B201                   mov     dl, $01
0051D16A   8B08                   mov     ecx, [eax]

* Reference to method TToolButton.SetEnabled(Boolean)
|
0051D16C   FF5164                 call    dword ptr [ecx+$64]
0051D16F   EB15                   jmp     0051D186
0051D171   8D55EC                 lea     edx, [ebp-$14]
0051D174   A188CA6100             mov     eax, dword ptr [$0061CA88]

* Reference to: System.LoadResString(PResStringRec):String;
|
0051D179   E8529EEEFF             call    00406FD0
0051D17E   8B45EC                 mov     eax, [ebp-$14]

* Reference to: Dialogs.ShowMessage(AnsiString);
|
0051D181   E85E86F2FF             call    004457E4
0051D186   33C0                   xor     eax, eax
0051D188   5A                     pop     edx
0051D189   59                     pop     ecx
0051D18A   59                     pop     ecx
0051D18B   648910                 mov     fs:[eax], edx

****** FINALLY
|
0051D18E   68A3D15100             push    $0051D1A3
0051D193   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.TObject.Free(TObject);
|
0051D196   E89D6BEEFF             call    00403D38
0051D19B   C3                     ret


* Reference to: System.@HandleFinally;
|
0051D19C   E92B73EEFF             jmp     004044CC
0051D1A1   EBF0                   jmp     0051D193

****** END
|
0051D1A3   33C0                   xor     eax, eax
0051D1A5   5A                     pop     edx
0051D1A6   59                     pop     ecx
0051D1A7   59                     pop     ecx
0051D1A8   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[��]�'
|
0051D1AB   68D5D15100             push    $0051D1D5
0051D1B0   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0051D1B3   E8B079EEFF             call    00404B68
0051D1B8   8D45F0                 lea     eax, [ebp-$10]
0051D1BB   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0051D1C0   E8C779EEFF             call    00404B8C
0051D1C5   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.@LStrClr(void;void);
|
0051D1C8   E89B79EEFF             call    00404B68
0051D1CD   C3                     ret


* Reference to: System.@HandleFinally;
|
0051D1CE   E9F972EEFF             jmp     004044CC
0051D1D3   EBDB                   jmp     0051D1B0

****** END
|
0051D1D5   5B                     pop     ebx
0051D1D6   8BE5                   mov     esp, ebp
0051D1D8   5D                     pop     ebp
0051D1D9   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.Print (TToolButton); TQRStandardPreview.PrintSetup (TToolButton)
Unresolved field offsets: OFFS_0344
Framework/API calls: method TToolButton.SetEnabled(Boolean);
    QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.QRPreviewPageAvailable(Sender : TObject);
begin
(*
0051D208   53                     push    ebx
0051D209   8BD8                   mov     ebx, eax
0051D20B   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);
|
0051D20D   E82EFAFFFF             call    0051CC40

* Reference to field TQRStandardPreview.OFFS_0344
|
0051D212   8B8344030000           mov     eax, [ebx+$0344]
0051D218   80B88500000002         cmp     byte ptr [eax+$0085], $02
0051D21F   751A                   jnz     0051D23B
0051D221   B201                   mov     dl, $01

* Reference to control TQRStandardPreview.PrintSetup : TToolButton
|
0051D223   8B831C030000           mov     eax, [ebx+$031C]
0051D229   8B08                   mov     ecx, [eax]

* Reference to method TToolButton.SetEnabled(Boolean)
|
0051D22B   FF5164                 call    dword ptr [ecx+$64]
0051D22E   B201                   mov     dl, $01

* Reference to control TQRStandardPreview.Print : TToolButton
|
0051D230   8B8320030000           mov     eax, [ebx+$0320]
0051D236   8B08                   mov     ecx, [eax]

* Reference to method TToolButton.SetEnabled(Boolean)
|
0051D238   FF5164                 call    dword ptr [ecx+$64]
0051D23B   5B                     pop     ebx
0051D23C   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.StatusBar (TStatusBar)
Unresolved field offsets: OFFS_034C
Project calls: Unit_00408494.Proc_00409950
Framework/API calls: ComCtrls.TStatusPanel.SetText(TStatusPanel;AnsiString);;
    ComCtrls.TStatusPanels.GetItem(TStatusPanels;Integer):TStatusPanel;
Strings/files/dialog text: '^[Y]�'; '��q����^[Y]�'
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.QRPreviewProgressUpdate(Sender : TObject);
begin
(*
0051D240   55                     push    ebp
0051D241   8BEC                   mov     ebp, esp
0051D243   6A00                   push    $00
0051D245   53                     push    ebx
0051D246   56                     push    esi
0051D247   8BD9                   mov     ebx, ecx
0051D249   8BF0                   mov     esi, eax
0051D24B   33C0                   xor     eax, eax
0051D24D   55                     push    ebp

* Possible String Reference to: '��q����^[Y]�'
|
0051D24E   68D9D25100             push    $0051D2D9

***** TRY
|
0051D253   64FF30                 push    dword ptr fs:[eax]
0051D256   648920                 mov     fs:[eax], esp

* Reference to field TQRStandardPreview.OFFS_034C
|
0051D259   8B864C030000           mov     eax, [esi+$034C]
0051D25F   83C005                 add     eax, +$05
0051D262   3BD8                   cmp     ebx, eax
0051D264   7C3A                   jl      0051D2A0
0051D266   8D55FC                 lea     edx, [ebp-$04]
0051D269   8BC3                   mov     eax, ebx

* Reference to: Unit_00408494.Proc_00409950
|
0051D26B   E8E0C6EEFF             call    00409950
0051D270   8D45FC                 lea     eax, [ebp-$04]
0051D273   BAF0D25100             mov     edx, $0051D2F0

* Reference to: System.@LStrCat;
|
0051D278   E8AB7BEEFF             call    00404E28
0051D27D   8B45FC                 mov     eax, [ebp-$04]
0051D280   50                     push    eax

* Reference to control TQRStandardPreview.StatusBar : TStatusBar
|
0051D281   8B86F0020000           mov     eax, [esi+$02F0]

* Reference to field TStatusBar.Panels : TStatusPanels
|
0051D287   8B8008020000           mov     eax, [eax+$0208]
0051D28D   33D2                   xor     edx, edx

* Reference to: ComCtrls.TStatusPanels.GetItem(TStatusPanels;Integer):TStatusPanel;
|
0051D28F   E8A032F6FF             call    00480534
0051D294   5A                     pop     edx

* Reference to: ComCtrls.TStatusPanel.SetText(TStatusPanel;AnsiString);
|
0051D295   E8F631F6FF             call    00480490

* Reference to field TQRStandardPreview.OFFS_034C
|
0051D29A   899E4C030000           mov     [esi+$034C], ebx
0051D2A0   85DB                   test    ebx, ebx
0051D2A2   7405                   jz      0051D2A9
0051D2A4   83FB64                 cmp     ebx, +$64
0051D2A7   751A                   jnz     0051D2C3

* Reference to control TQRStandardPreview.StatusBar : TStatusBar
|
0051D2A9   8B86F0020000           mov     eax, [esi+$02F0]

* Reference to field TStatusBar.Panels : TStatusPanels
|
0051D2AF   8B8008020000           mov     eax, [eax+$0208]
0051D2B5   33D2                   xor     edx, edx

* Reference to: ComCtrls.TStatusPanels.GetItem(TStatusPanels;Integer):TStatusPanel;
|
0051D2B7   E87832F6FF             call    00480534
0051D2BC   33D2                   xor     edx, edx

* Reference to: ComCtrls.TStatusPanel.SetText(TStatusPanel;AnsiString);
|
0051D2BE   E8CD31F6FF             call    00480490
0051D2C3   33C0                   xor     eax, eax
0051D2C5   5A                     pop     edx
0051D2C6   59                     pop     ecx
0051D2C7   59                     pop     ecx
0051D2C8   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]�'
|
0051D2CB   68E0D25100             push    $0051D2E0
0051D2D0   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0051D2D3   E89078EEFF             call    00404B68
0051D2D8   C3                     ret


* Reference to: System.@HandleFinally;
|
0051D2D9   E9EE71EEFF             jmp     004044CC
0051D2DE   EBF0                   jmp     0051D2D0

****** END
|
0051D2E0   5E                     pop     esi
0051D2E1   5B                     pop     ebx
0051D2E2   59                     pop     ecx
0051D2E3   5D                     pop     ebp
0051D2E4   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
  Unknown: no symbolic resource labels found; resources are represented only by raw offsets or indirect calls.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview.FormCreate(Sender : TObject);
begin
(*

* Reference to field TQRStandardPreview.HorzScrollBar : TControlScrollBar
|
0051D2F4   8B9008020000           mov     edx, [eax+$0208]

* Reference to field TControlScrollBar.Tracking : Boolean
|
0051D2FA   C6421D01               mov     byte ptr [edx+$1D], $01

* Reference to field TQRStandardPreview.VertScrollBar : TControlScrollBar
|
0051D2FE   8B800C020000           mov     eax, [eax+$020C]

* Reference to field TControlScrollBar.Tracking : Boolean
|
0051D304   C6401D01               mov     byte ptr [eax+$1D], $01
0051D308   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
UI/forms: TQRStandardPreview.QRPreview (TQRPreview); TQRStandardPreview.StatusBar (TStatusBar)
Unresolved field offsets: OFFS_023C; OFFS_0240
Project calls: Unit_00408494.Proc_00409950
Framework/API calls: ComCtrls.TStatusPanel.SetText(TStatusPanel;AnsiString);;
    ComCtrls.TStatusPanels.GetItem(TStatusPanels;Integer):TStatusPanel;;
    System.LoadResString(PResStringRec):String;; System.Proc_00404EE0
Strings/files/dialog text: '[��]�'; '��w����[��]�'
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview._PROC_0051CC40(Sender : TObject);
begin
(*
0051CC40   55                     push    ebp
0051CC41   8BEC                   mov     ebp, esp
0051CC43   33C9                   xor     ecx, ecx
0051CC45   51                     push    ecx
0051CC46   51                     push    ecx
0051CC47   51                     push    ecx
0051CC48   51                     push    ecx
0051CC49   51                     push    ecx
0051CC4A   53                     push    ebx
0051CC4B   8BD8                   mov     ebx, eax
0051CC4D   33C0                   xor     eax, eax
0051CC4F   55                     push    ebp

* Possible String Reference to: '��w����[��]�'
|
0051CC50   6803CD5100             push    $0051CD03

***** TRY
|
0051CC55   64FF30                 push    dword ptr fs:[eax]
0051CC58   648920                 mov     fs:[eax], esp
0051CC5B   8D55F8                 lea     edx, [ebp-$08]
0051CC5E   A1A8C66100             mov     eax, dword ptr [$0061C6A8]

* Reference to: System.LoadResString(PResStringRec):String;
|
0051CC63   E868A3EEFF             call    00406FD0
0051CC68   FF75F8                 push    dword ptr [ebp-$08]
0051CC6B   6818CD5100             push    $0051CD18
0051CC70   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CC73   8B8340030000           mov     eax, [ebx+$0340]

* Reference to field TQRPreview.OFFS_023C
|
0051CC79   8B803C020000           mov     eax, [eax+$023C]

* Reference to: Unit_00408494.Proc_00409950
|
0051CC7F   E8CCCCEEFF             call    00409950
0051CC84   FF75F4                 push    dword ptr [ebp-$0C]
0051CC87   6818CD5100             push    $0051CD18
0051CC8C   8D55F0                 lea     edx, [ebp-$10]
0051CC8F   A1FCC86100             mov     eax, dword ptr [$0061C8FC]

* Reference to: System.LoadResString(PResStringRec):String;
|
0051CC94   E837A3EEFF             call    00406FD0
0051CC99   FF75F0                 push    dword ptr [ebp-$10]
0051CC9C   6818CD5100             push    $0051CD18
0051CCA1   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TQRStandardPreview.QRPreview : TQRPreview
|
0051CCA4   8B8340030000           mov     eax, [ebx+$0340]

* Reference to field TQRPreview.OFFS_0240
|
0051CCAA   8B8040020000           mov     eax, [eax+$0240]
0051CCB0   8B406C                 mov     eax, [eax+$6C]

* Reference to: Unit_00408494.Proc_00409950
|
0051CCB3   E898CCEEFF             call    00409950
0051CCB8   FF75EC                 push    dword ptr [ebp-$14]
0051CCBB   8D45FC                 lea     eax, [ebp-$04]
0051CCBE   BA07000000             mov     edx, $00000007

* Reference to: System.Proc_00404EE0
|
0051CCC3   E81882EEFF             call    00404EE0
0051CCC8   8B45FC                 mov     eax, [ebp-$04]
0051CCCB   50                     push    eax

* Reference to control TQRStandardPreview.StatusBar : TStatusBar
|
0051CCCC   8B83F0020000           mov     eax, [ebx+$02F0]

* Reference to field TStatusBar.Panels : TStatusPanels
|
0051CCD2   8B8008020000           mov     eax, [eax+$0208]
0051CCD8   BA01000000             mov     edx, $00000001

* Reference to: ComCtrls.TStatusPanels.GetItem(TStatusPanels;Integer):TStatusPanel;
|
0051CCDD   E85238F6FF             call    00480534
0051CCE2   5A                     pop     edx

* Reference to: ComCtrls.TStatusPanel.SetText(TStatusPanel;AnsiString);
|
0051CCE3   E8A837F6FF             call    00480490
0051CCE8   33C0                   xor     eax, eax
0051CCEA   5A                     pop     edx
0051CCEB   59                     pop     ecx
0051CCEC   59                     pop     ecx
0051CCED   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[��]�'
|
0051CCF0   680ACD5100             push    $0051CD0A
0051CCF5   8D45EC                 lea     eax, [ebp-$14]
0051CCF8   BA05000000             mov     edx, $00000005

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0051CCFD   E88A7EEEFF             call    00404B8C
0051CD02   C3                     ret


* Reference to: System.@HandleFinally;
|
0051CD03   E9C477EEFF             jmp     004044CC
0051CD08   EBEB                   jmp     0051CCF5

****** END
|
0051CD0A   5B                     pop     ebx
0051CD0B   8BE5                   mov     esp, ebp
0051CD0D   5D                     pop     ebp
0051CD0E   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
Framework/API calls: Forms.TCustomForm.Show(TCustomForm);;
    QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview._PROC_0051CE14(Sender : TObject);
begin
(*
0051CE14   53                     push    ebx
0051CE15   8BD8                   mov     ebx, eax
0051CE17   8BC3                   mov     eax, ebx

* Reference to: Forms.TCustomForm.Show(TCustomForm);
|
0051CE19   E81ECEF4FF             call    00469C3C
0051CE1E   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.UpdateInfo(TQRStandardPreview);
|
0051CE20   E81BFEFFFF             call    0051CC40
0051CE25   5B                     pop     ebx
0051CE26   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
Framework/API calls: QRPrev.TQRStandardPreview.ExitClick(TQRStandardPreview;TObject);;
    QRPrev.TQRStandardPreview.FirstPageClick(TQRStandardPreview;TObject);;
    QRPrev.TQRStandardPreview.LastPageClick(TQRStandardPreview;TObject);;
    QRPrev.TQRStandardPreview.NextPageClick(TQRStandardPreview;TObject);;
    QRPrev.TQRStandardPreview.PrevPageClick(TQRStandardPreview;TObject);
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview._PROC_0051CE47(Sender : TObject);
begin
(*
0051CE47   00CB                   add     bl, cl
0051CE49   CE                     into
0051CE4A   51                     push    ecx
0051CE4B   00CB                   add     bl, cl
0051CE4D   CE                     into
0051CE4E   51                     push    ecx
0051CE4F   00CB                   add     bl, cl
0051CE51   CE                     into
0051CE52   51                     push    ecx
0051CE53   00CB                   add     bl, cl
0051CE55   CE                     into
0051CE56   51                     push    ecx
0051CE57   00CB                   add     bl, cl
0051CE59   CE                     into
0051CE5A   51                     push    ecx
0051CE5B   008CCE51006CCE         add     [esi+ecx*8+$CE6C0051], cl
0051CE62   51                     push    ecx
0051CE63   00B7CE5100AC           add     [edi+$AC0051CE], dh
0051CE69   CE                     into
0051CE6A   51                     push    ecx
0051CE6B   00A0D0CE5100           add     [eax+$51CED0], ah
0051CE71   3A4508                 cmp     al, byte ptr [ebp+$08]
0051CE74   750B                   jnz     0051CE81
0051CE76   8BD3                   mov     edx, ebx
0051CE78   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.LastPageClick(TQRStandardPreview;TObject);
|
0051CE7A   E855FFFFFF             call    0051CDD4
0051CE7F   EB4A                   jmp     0051CECB
0051CE81   8BD3                   mov     edx, ebx
0051CE83   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.NextPageClick(TQRStandardPreview;TObject);
|
0051CE85   E82AFFFFFF             call    0051CDB4
0051CE8A   EB3F                   jmp     0051CECB
0051CE8C   A0D0CE5100             mov     al, byte ptr [$0051CED0]
0051CE91   3A4508                 cmp     al, byte ptr [ebp+$08]
0051CE94   750B                   jnz     0051CEA1
0051CE96   8BD3                   mov     edx, ebx
0051CE98   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.FirstPageClick(TQRStandardPreview;TObject);
|
0051CE9A   E8D9FEFFFF             call    0051CD78
0051CE9F   EB2A                   jmp     0051CECB
0051CEA1   8BD3                   mov     edx, ebx
0051CEA3   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.PrevPageClick(TQRStandardPreview;TObject);
|
0051CEA5   E8EAFEFFFF             call    0051CD94
0051CEAA   EB1F                   jmp     0051CECB
0051CEAC   8BD3                   mov     edx, ebx
0051CEAE   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.FirstPageClick(TQRStandardPreview;TObject);
|
0051CEB0   E8C3FEFFFF             call    0051CD78
0051CEB5   EB14                   jmp     0051CECB
0051CEB7   8BD3                   mov     edx, ebx
0051CEB9   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.LastPageClick(TQRStandardPreview;TObject);
|
0051CEBB   E814FFFFFF             call    0051CDD4
0051CEC0   EB09                   jmp     0051CECB
0051CEC2   8BD3                   mov     edx, ebx
0051CEC4   8BC3                   mov     eax, ebx

* Reference to: QRPrev.TQRStandardPreview.ExitClick(TQRStandardPreview;TObject);
|
0051CEC6   E835FFFFFF             call    0051CE00
0051CECB   5B                     pop     ebx
0051CECC   5D                     pop     ebp
0051CECD   C20400                 ret     $0004

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
  Unknown: no symbolic resource labels found; resources are represented only by raw offsets or indirect calls.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview._PROC_0051CED0(Sender : TObject);
begin
(*
0051CED0   0400                   add     al, +$00
0051CED2   0000                   add     [eax], al

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
Strings/files/dialog text: ']Ë��-��a'; '�q����]Ë��-��a'
  Unknown: raw binary addresses, unlabelled object offsets, and indirect targets are unresolved.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview._PROC_0051D30D(Sender : TObject);
begin
(*
0051D30D   8BEC                   mov     ebp, esp
0051D30F   33C0                   xor     eax, eax
0051D311   55                     push    ebp

* Possible String Reference to: '�q����]Ë��-��a'
|
0051D312   6831D35100             push    $0051D331

***** TRY
|
0051D317   64FF30                 push    dword ptr fs:[eax]
0051D31A   648920                 mov     fs:[eax], esp
0051D31D   FF05BCDE6100           inc     dword ptr [$0061DEBC]
0051D323   33C0                   xor     eax, eax
0051D325   5A                     pop     edx
0051D326   59                     pop     ecx
0051D327   59                     pop     ecx
0051D328   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ë��-��a'
|
0051D32B   6838D35100             push    $0051D338
0051D330   C3                     ret


* Reference to: System.@HandleFinally;
|
0051D331   E99671EEFF             jmp     004044CC
0051D336   EBF8                   jmp     0051D330

****** END
|
0051D338   5D                     pop     ebp
0051D339   C3                     ret

*)
end;

{ ASM listing resource map; extracted from commented binary evidence only.
  Unknown: no symbolic resource labels found; resources are represented only by raw offsets or indirect calls.
  This is not a runtime dependency map; original offsets refer to the decompiled binary layout.
}
procedure TQRStandardPreview._PROC_0051D33C(Sender : TObject);
begin
(*
0051D33C   832DBCDE610001         sub     dword ptr [$0061DEBC], +$01
0051D343   C3                     ret

*)
end;

end.